package de.ostms.lc.user.service;
import de.ostms.lc.user.api.*;import de.ostms.lc.user.domain.*;import de.ostms.lc.user.repository.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class UserService {
 private final AppUserRepository repo;private final AppRoleRepository roles;private final PasswordEncoder encoder;private final IdentityCredentialService credentials;private final TenantAdministrationLock administration;public UserService(AppUserRepository r,AppRoleRepository roles,PasswordEncoder e,TenantAdministrationLock administration,IdentityCredentialService credentials){repo=r;this.roles=roles;encoder=e;this.administration=administration;this.credentials=credentials;}
 @Transactional(propagation=org.springframework.transaction.annotation.Propagation.MANDATORY) public UserView getForAdministration(UUID id){administration.acquire();return UserView.of(one(id));}public List<UserView> all(){return repo.findAllByOrderByUsernameAsc().stream().map(UserView::of).toList();}public List<AssignableUser> assignable(){return (de.ostms.lc.tenant.domain.Tenant.DEFAULT_ID.equals(de.ostms.lc.tenant.domain.TenantContext.currentId())?repo.findAllByActiveTrueOrderByDisplayNameAsc():repo.findAssignableMembershipUsers()).stream().map(u->new AssignableUser(u.getUsername(),u.getDisplayName())).toList();}public boolean isAssignable(String username){return username!=null&&(de.ostms.lc.tenant.domain.Tenant.DEFAULT_ID.equals(de.ostms.lc.tenant.domain.TenantContext.currentId())?repo.existsAssignableUsername(username.trim()):repo.findAssignableMembershipUsers().stream().anyMatch(u->u.getUsername().equalsIgnoreCase(username.trim())));}
 @Transactional public UserView create(UserRequest r){throw new org.springframework.security.access.AccessDeniedException("Global account creation is available only in platform administration.");}
 @Transactional public UserView update(UUID id,UserRequest r,String current){administration.acquire();AppUser u=one(id);if(identityChanges(u,r))requireExclusiveIdentity(u);if(repo.findByUsernameIgnoreCase(r.username()).filter(x->!x.getId().equals(id)).isPresent())throw new IllegalArgumentException("Benutzername existiert bereits.");AppRole role=role(r.roleId());boolean removesLastAdmin=u.getRole()==UserRole.ADMIN&&u.isActive()&&(role.getBaseRole()!=UserRole.ADMIN||!r.active())&&repo.countByRoleAndActiveTrue(UserRole.ADMIN)<=1;if(removesLastAdmin)throw new IllegalArgumentException("Der letzte aktive Administrator kann nicht deaktiviert oder herabgestuft werden.");if(u.getUsername().equalsIgnoreCase(current)&&!r.active())throw new IllegalArgumentException("Das eigene Konto kann nicht deaktiviert werden.");if(u.getUsername().equalsIgnoreCase(current)&&!role.getPermissions().contains(UserPermission.USER_MANAGE))throw new IllegalArgumentException("Die eigene Rolle muss die Benutzerverwaltung erlauben.");apply(u,r,false);return UserView.of(u);}
 @Transactional public void delete(UUID id,String current){administration.acquire();AppUser u=one(id);requireExclusiveIdentity(u);if(u.getUsername().equalsIgnoreCase(current))throw new IllegalArgumentException("Das eigene Konto kann nicht gelöscht werden.");if(u.getRole()==UserRole.ADMIN&&u.isActive()&&repo.countByRoleAndActiveTrue(UserRole.ADMIN)<=1)throw new IllegalArgumentException("Der letzte aktive Administrator kann nicht gelöscht werden.");repo.delete(u);}
 @Transactional public void changePassword(String username,String currentPassword,String newPassword){credentials.changeOwnPassword(username,currentPassword,newPassword);}
 static void validatePassword(String password){if(password==null||password.length()<10)throw new IllegalArgumentException("Das Passwort muss mindestens 10 Zeichen lang sein.");if(!password.matches(".*[A-ZÄÖÜ].*")||!password.matches(".*[a-zäöüß].*")||!password.matches(".*\\d.*"))throw new IllegalArgumentException("Das Passwort muss Großbuchstaben, Kleinbuchstaben und eine Zahl enthalten.");}
 private boolean identityChanges(AppUser u,UserRequest r){return !Objects.equals(u.getUsername(),clean(r.username()).toLowerCase(Locale.ROOT))||!Objects.equals(u.getDisplayName(),clean(r.displayName()))||!Objects.equals(u.getEmail(),UserEmail.required(r.email()))||u.isActive()!=r.active()||(r.password()!=null&&!r.password().isBlank());}
 private void requireExclusiveIdentity(AppUser u){if(u.isInvitationPending())throw new org.springframework.security.access.AccessDeniedException("Pending invitations are managed only in platform administration.");if(u.isPlatformAdministrator())throw new org.springframework.security.access.AccessDeniedException("Platform administrator identities cannot be changed through tenant administration.");if(repo.countForeignMemberships(u.getId())>0)throw new org.springframework.security.access.AccessDeniedException("Shared identities cannot be changed through tenant user administration.");}
 private void apply(AppUser u,UserRequest r,boolean creating){u.setEmail(UserEmail.required(r.email()));u.setUsername(clean(r.username()).toLowerCase(Locale.ROOT));u.setDisplayName(clean(r.displayName()));u.setAssignedRole(role(r.roleId()));u.setActive(r.active());if(r.password()!=null&&!r.password().isBlank()){validatePassword(r.password());u.setPasswordHash(encoder.encode(r.password()));}else if(creating)throw new IllegalArgumentException("Passwort fehlt.");}
 private AppRole role(UUID id){return roles.findById(id).orElseThrow(()->new NoSuchElementException("Rolle nicht gefunden"));}private AppUser one(UUID id){return repo.findById(id).orElseThrow(()->new NoSuchElementException("Benutzer nicht gefunden"));}private String clean(String v){return v==null?"":v.trim();}
}
