package de.ostms.lc.document.service;
import de.ostms.lc.document.domain.DocumentType;
import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.*;
class DocumentClassifierTest {
 @Test void longWhitespaceInputsDoNotBacktrackAcrossOptionalSwiftSeparators(){org.junit.jupiter.api.Assertions.assertTimeoutPreemptively(java.time.Duration.ofSeconds(2),()->{String spaces=" ".repeat(100_000);assertThat(DocumentClassifier.classify("mt"+spaces+"x.pdf",spaces+":X").suggestedType()).isNull();});}
 @Test void existingOpenInboxItemsUseCurrentRulesWithoutReplacingStoredHistory(){var item=new de.ostms.lc.document.domain.DocumentInboxItem();item.setStatus("OPEN");item.setOriginalFilename("scan.pdf");item.setExtractedText("Avisierung eines Dokumentenakkreditivs");String old=ClassificationHistory.automatic("scan.pdf","");item.setClassificationHistoryJson(old);var view=de.ostms.lc.document.api.DocumentInboxItemView.from(item,java.util.List.of());assertThat(view.classification().suggestedType()).isEqualTo(DocumentType.ADVISING_LETTER);assertThat(item.getClassificationHistoryJson()).isEqualTo(old);}
 @Test void recognizesMt700WithoutMisclassifyingRequiredDocuments(){var result=DocumentClassifier.classify("scan.pdf","  :20:LC123\n :40A:IRREVOCABLE\n :32B:EUR1000,00\n:46A:\nCOMMERCIAL INVOICE\nPACKING LIST");assertThat(result.suggestedType()).isEqualTo(DocumentType.SWIFT_MT700);}
 @Test void recognizesAdviceHeadingWithAttachedSwift(){assertThat(DocumentClassifier.classify("scan.pdf","Avisierung eines Dokumentenakkreditivs\nUnsere Referenz: ABC\n:20:ABC\n:40A:IRREVOCABLE\n:32B:EUR1000").suggestedType()).isEqualTo(DocumentType.ADVISING_LETTER);assertThat(DocumentClassifier.classify("scan.pdf","Advice of documentary credit\nDetails").suggestedType()).isEqualTo(DocumentType.ADVISING_LETTER);}
 @Test void filenameHintsRemainUncertain(){assertThat(DocumentClassifier.classify("MT700_blanko.pdf",null).status()).isEqualTo("REVIEW");assertThat(DocumentClassifier.classify("Avisierungsschreiben.pdf",null).suggestedType()).isEqualTo(DocumentType.ADVISING_LETTER);}
 @Test void swiftConditionsAreNotDocumentHeadings(){assertThat(DocumentClassifier.classify("lc.pdf",":20:LC123\n:46A:\nCOMMERCIAL INVOICE").suggestedType()).isNull();}
 @Test void recognizesAllRequiredHeadings(){String[] headings={"COMMERCIAL INVOICE","PACKING LIST","BILL OF LADING","AIR WAYBILL","CERTIFICATE OF ORIGIN","INSURANCE CERTIFICATE"};DocumentType[] types={DocumentType.COMMERCIAL_INVOICE,DocumentType.PACKING_LIST,DocumentType.BILL_OF_LADING,DocumentType.AIR_WAYBILL,DocumentType.CERTIFICATE_OF_ORIGIN,DocumentType.INSURANCE_CERTIFICATE};for(int i=0;i<headings.length;i++){var result=DocumentClassifier.classify("scan.pdf",headings[i]+"\nDetails");assertThat(result.suggestedType()).isEqualTo(types[i]);assertThat(result.score()).isEqualTo(.9);}}
 @Test void conflictsAndMentionsDoNotBecomeCertain(){assertThat(DocumentClassifier.classify("scan.pdf","COMMERCIAL INVOICE\nPACKING LIST").status()).isEqualTo("AMBIGUOUS");assertThat(DocumentClassifier.classify("scan.pdf","Please present a commercial invoice and packing list").status()).isEqualTo("UNKNOWN");}
 @Test void filenameIsOnlyWeakHint(){var result=DocumentClassifier.classify("packing_list.pdf",null);assertThat(result.suggestedType()).isEqualTo(DocumentType.PACKING_LIST);assertThat(result.status()).isEqualTo("REVIEW");assertThat(result.score()).isEqualTo(.55);}
 @Test void manualChoiceRetainsAutoEvidence(){var automatic=ClassificationHistory.automatic("scan.pdf","COMMERCIAL INVOICE");var manual=ClassificationHistory.manual(automatic,DocumentType.PACKING_LIST,"reviewer");assertThat(ClassificationHistory.read(manual)).hasSize(2);assertThat(ClassificationHistory.suggestion(manual).suggestedType()).isEqualTo(DocumentType.COMMERCIAL_INVOICE);assertThat(manual).contains("reviewer","MANUAL","PACKING_LIST");}
}
