package de.corporate.lc.user.service;
import de.corporate.lc.tenant.domain.*;
import de.corporate.lc.tenant.repository.TenantRepository;
import de.corporate.lc.user.domain.*;
import de.corporate.lc.user.repository.*;
import org.junit.jupiter.api.*;
import java.util.*;
import java.time.Instant;
import static org.mockito.Mockito.*;
import static org.assertj.core.api.Assertions.*;
class InvitationMailQueueTest {
 final PlatformInvitationRepository invitations=mock(PlatformInvitationRepository.class);final AppUserRepository users=mock(AppUserRepository.class);final AppRoleRepository roles=mock(AppRoleRepository.class);final TenantRepository tenants=mock(TenantRepository.class);final TenantAdministrationLock lock=mock(TenantAdministrationLock.class);final PlatformInvitationMailService delivery=mock(PlatformInvitationMailService.class);final InvitationMailCipher cipher=new InvitationMailCipher("SyntheticEncryptionKeyOnlyAtLeast32Characters");final InvitationMailQueue queue=new InvitationMailQueue(invitations,users,roles,tenants,lock,cipher,delivery);
 final UUID userId=UUID.randomUUID(),issuer=UUID.randomUUID();final AppUser user=new AppUser();final AppRole role=new AppRole();final String token="A".repeat(43);PlatformInvitation saved;PlatformInvitationService.MailRequested event;
 @BeforeEach void setup(){user.setInvitationPending(true);user.setActive(false);user.setEmail("synthetic@example.invalid");user.setPasswordHash("hash");org.springframework.test.util.ReflectionTestUtils.setField(role,"id",UUID.randomUUID());saved=new PlatformInvitation(CredentialStamp.of(token),userId,issuer,Tenant.DEFAULT_ID,role.getId(),PlatformInvitationService.roleStamp(role),CredentialStamp.of("hash"),user.getEmail(),Instant.now().plusSeconds(3600));event=new PlatformInvitationService.MailRequested(userId,token,"synthetic",user.getEmail(),"default","Default");when(invitations.findById(saved.getTokenHash())).thenReturn(Optional.of(saved));when(invitations.findDue(any(),any())).thenReturn(List.of(saved));when(users.findForPasswordReset(userId)).thenReturn(Optional.of(user));when(users.hasLivePlatformAccess(issuer)).thenReturn(true);when(tenants.findById(Tenant.DEFAULT_ID)).thenReturn(Optional.of(new Tenant()));when(roles.findById(role.getId())).thenReturn(Optional.of(role));queue.enqueue(event);}
 @Test void enqueuePersistsCiphertextAndDueTime(){assertThat(saved.getEncryptedMailPayload()).doesNotContain(token).doesNotContain(user.getEmail());assertThat(saved.getNextDeliveryAttempt()).isNotNull();assertThat(saved.toString()).doesNotContain(token);}
 @Test void successfulSendErasesPayloadAndRestoresCallerScope(){doAnswer(i->{saved.setDeliveryStatus("SENT");return null;}).when(delivery).deliver(any());var selected=UUID.randomUUID();try(var scope=TenantContext.open(selected)){queue.deliverNext();assertThat(TenantContext.currentId()).isEqualTo(selected);}assertThat(saved.getDeliveryAttempts()).isEqualTo(1);assertThat(saved.getEncryptedMailPayload()).isNull();assertThat(saved.getNextDeliveryAttempt()).isNull();verify(delivery).deliver(event);}
 @Test void smtpRetriesWithBackoffAndStopsAfterFive(){doAnswer(i->{saved.setDeliveryStatus("MAIL_FAILED");return null;}).when(delivery).deliver(any());queue.deliverNext();assertThat(saved.getDeliveryStatus()).isEqualTo("MAIL_RETRY");assertThat(saved.getNextDeliveryAttempt()).isAfter(Instant.now().plusSeconds(20));for(int i=0;i<4;i++)queue.deliverNext();assertThat(saved.getDeliveryAttempts()).isEqualTo(5);assertThat(saved.getDeliveryStatus()).isEqualTo("MAIL_FAILED");assertThat(saved.getDeliveryError()).isEqualTo("SMTP_FAILED");assertThat(saved.getEncryptedMailPayload()).isNull();}
 @Test void revokedIssuerCancelsWithoutSending(){when(users.hasLivePlatformAccess(issuer)).thenReturn(false);queue.deliverNext();verifyNoInteractions(delivery);assertThat(saved.getDeliveryStatus()).isEqualTo("MAIL_CANCELLED");assertThat(saved.getEncryptedMailPayload()).isNull();}
 @Test void roleOrCredentialChangesCancelDelivery(){user.setPasswordHash("new");queue.deliverNext();verifyNoInteractions(delivery);assertThat(saved.getDeliveryError()).isEqualTo("ACCESS_CHANGED");}
 @Test void corruptPayloadFailsWithoutLeakingOrSending(){saved.setEncryptedMailPayload("corrupt");queue.deliverNext();verifyNoInteractions(delivery);assertThat(saved.getDeliveryError()).isEqualTo("PAYLOAD_UNREADABLE");assertThat(saved.getEncryptedMailPayload()).isNull();}
 @Test void noDueInvitationDoesNotSend(){when(invitations.findDue(any(),any())).thenReturn(List.of());queue.deliverNext();verifyNoInteractions(delivery);verify(invitations).clearExpiredMail(any());}
}
