package de.corporate.lc.user.service;
import de.corporate.lc.audit.service.AuditService;
import de.corporate.lc.tenant.domain.*;
import de.corporate.lc.tenant.repository.*;
import de.corporate.lc.user.domain.*;
import de.corporate.lc.user.repository.*;
import org.junit.jupiter.api.*;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

class PlatformInvitationServiceTest {
 final PlatformAdministrationService platform=mock(PlatformAdministrationService.class);final PlatformAccountCreationService creation=mock(PlatformAccountCreationService.class);
 final AppUserRepository users=mock(AppUserRepository.class);final AppRoleRepository roles=mock(AppRoleRepository.class);final TenantRepository tenants=mock(TenantRepository.class);final PlatformInvitationRepository invitations=mock(PlatformInvitationRepository.class);final TenantMembershipSuspensionRepository suspensions=mock(TenantMembershipSuspensionRepository.class);final TenantMembershipProvisioningStore memberships=mock(TenantMembershipProvisioningStore.class);final TenantAdministrationLock lock=mock(TenantAdministrationLock.class);final PasswordEncoder encoder=mock(PasswordEncoder.class);final AuditService audit=mock(AuditService.class);final ApplicationEventPublisher events=mock(ApplicationEventPublisher.class);
 final PlatformInvitationService service=new PlatformInvitationService(platform,creation,users,roles,tenants,invitations,suspensions,memberships,lock,encoder,audit,events,true,"sender@example.invalid");
 final UUID tenantId=UUID.randomUUID(),roleId=UUID.randomUUID(),userId=UUID.randomUUID(),issuerId=UUID.randomUUID();
 final org.springframework.security.core.Authentication auth=UsernamePasswordAuthenticationToken.authenticated("admin",null,List.of());
 final String token=Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[32]),hash=CredentialStamp.of(token);
 AppUser user,actor;AppRole role;Tenant tenant;PlatformInvitation saved;
 @BeforeEach void setup(){
  actor=new AppUser();ReflectionTestUtils.setField(actor,"id",issuerId);actor.setUsername("admin");actor.setPlatformAdministrator(true);actor.setTotpEnabled(true);
  user=new AppUser();ReflectionTestUtils.setField(user,"id",userId);user.setUsername("synthetic-invite");user.setDisplayName("Synthetic Invite");user.setEmail("invite@example.invalid");user.setPasswordHash("synthetic-hash");user.setActive(false);user.setInvitationPending(true);
  tenant=new Tenant();ReflectionTestUtils.setField(tenant,"id",tenantId);ReflectionTestUtils.setField(tenant,"code","synthetic-invite");
  try(var scope=TenantContext.open(tenantId)){role=new AppRole();ReflectionTestUtils.setField(role,"id",roleId);role.setName("Synthetic viewer");}
  saved=invitation(Instant.now().plusSeconds(3600));
  when(platform.enabled(auth)).thenReturn(true);when(users.findByUsernameIgnoreCase("admin")).thenReturn(Optional.of(actor));when(users.findById(issuerId)).thenReturn(Optional.of(actor));when(users.findById(userId)).thenReturn(Optional.of(user));when(users.findForPasswordReset(userId)).thenReturn(Optional.of(user));when(tenants.findById(tenantId)).thenReturn(Optional.of(tenant));when(roles.findById(roleId)).thenReturn(Optional.of(role));when(invitations.findById(hash)).thenReturn(Optional.of(saved));when(invitations.existsById(hash)).thenReturn(true);when(invitations.findByUserId(userId)).thenReturn(Optional.of(saved));when(encoder.encode(any())).thenReturn("new-synthetic-hash");
 }
 PlatformInvitation invitation(Instant expires){return new PlatformInvitation(hash,userId,issuerId,tenantId,roleId,PlatformInvitationService.roleStamp(role),CredentialStamp.of(user.getPasswordHash()),user.getEmail(),expires);}
 @Test void localRoleCannotIssueOrListInvitations(){when(platform.enabled(auth)).thenReturn(false);assertThatThrownBy(()->service.invite("new","New","new@example.invalid",tenantId,roleId,auth)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);assertThatThrownBy(()->service.list(auth)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);verifyNoInteractions(lock,creation,events);}
 @Test void mailDisabledDoesNotCreateIdentity(){var disabled=new PlatformInvitationService(platform,creation,users,roles,tenants,invitations,suspensions,memberships,lock,encoder,audit,events,false,"");assertThatThrownBy(()->disabled.invite("new","New","new@example.invalid",tenantId,roleId,auth)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("not configured");verifyNoInteractions(creation,events);}
 @Test void roleFromAnotherTenantFailsClosed(){ReflectionTestUtils.setField(role,"tenantId",UUID.randomUUID());assertThatThrownBy(()->service.invite("new","New","new@example.invalid",tenantId,roleId,auth)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);verifyNoInteractions(creation,events);}
 @Test void issueUsesHashedSingleUseSecretAndDefersMembership(){when(users.findByUsernameIgnoreCase("synthetic-invite")).thenReturn(Optional.of(user));var result=service.invite(user.getUsername(),user.getDisplayName(),user.getEmail(),tenantId,roleId,auth);assertThat(result.userId()).isEqualTo(userId);assertThat(result.status()).isEqualTo("PENDING_MAIL");assertThat(result.expiresAt()).isAfter(Instant.now().plusSeconds(86000));var event=org.mockito.ArgumentCaptor.forClass(Object.class);verify(events).publishEvent(event.capture());var requested=(PlatformInvitationService.MailRequested)event.getValue();assertThat(requested.token()).matches("[A-Za-z0-9_-]{43}");assertThat(requested.toString()).doesNotContain(requested.token());var captured=org.mockito.ArgumentCaptor.forClass(PlatformInvitation.class);verify(invitations).saveAndFlush(captured.capture());assertThat(captured.getValue().getTokenHash()).isEqualTo(CredentialStamp.of(requested.token()));assertThat(captured.getValue().toString()).doesNotContain(requested.token());verifyNoInteractions(memberships);assertThat(user.isActive()).isFalse();}
 @Test void mismatchedPendingIdentityCannotBeReinvited(){when(users.findByUsernameIgnoreCase(user.getUsername())).thenReturn(Optional.of(user));assertThatThrownBy(()->service.invite(user.getUsername(),user.getDisplayName(),"other@example.invalid",tenantId,roleId,auth)).isInstanceOf(IllegalArgumentException.class);verify(events,never()).publishEvent(any(Object.class));}
 @Test void revokeDeletesTokenButKeepsBlockedIdentity(){service.revoke(userId,auth);verify(invitations).deleteForUser(userId);assertThat(user.isActive()).isFalse();assertThat(user.isInvitationPending()).isTrue();verifyNoInteractions(memberships);}
 @Test void resendReplacesPreviousTokenAndRechecksCurrentTargetRole(){service.resend(userId,auth);verify(invitations).deleteForUser(userId);verify(invitations).flush();verify(events).publishEvent(any(Object.class));verifyNoInteractions(memberships);}
 @Test void acceptanceSetsPasswordAndExplicitForeignMembershipOnly(){UUID caller=UUID.randomUUID();try(var scope=TenantContext.open(caller)){service.accept(token,"SyntheticNew123!");assertThat(TenantContext.currentId()).isEqualTo(caller);}assertThat(user.isActive()).isTrue();assertThat(user.isInvitationPending()).isFalse();assertThat(user.isPlatformAdministrator()).isFalse();assertThat(user.getPasswordHash()).isEqualTo("new-synthetic-hash");verify(memberships).create(tenantId,userId,roleId);verifyNoInteractions(suspensions);verify(invitations).deleteForUser(userId);verify(audit).recordChangeInTransaction(any(),eq("PLATFORM_INVITATION_ACCEPTED"),eq("INVITATION"),eq(userId),anyString(),contains("tenantId"),eq("{\"status\":\"ACCEPTED\"}"));}
 @Test void revokedCachedTokenCannotBeAccepted(){when(invitations.existsById(hash)).thenReturn(false);assertThatThrownBy(()->service.accept(token,"SyntheticNew123!")).isInstanceOf(IllegalArgumentException.class);verifyNoInteractions(encoder,memberships);}
 @Test void defaultTenantIsGrantedOnlyByExplicitInvitationAndClearsItsSuspension(){ReflectionTestUtils.setField(role,"tenantId",Tenant.DEFAULT_ID);when(tenants.findById(Tenant.DEFAULT_ID)).thenReturn(Optional.of(new Tenant()));var homeInvitation=new PlatformInvitation(hash,userId,issuerId,Tenant.DEFAULT_ID,roleId,PlatformInvitationService.roleStamp(role),CredentialStamp.of(user.getPasswordHash()),user.getEmail(),Instant.now().plusSeconds(3600));when(invitations.findById(hash)).thenReturn(Optional.of(homeInvitation));var state=new TenantMembershipSuspension(userId);state.setSuspended(true);when(suspensions.findByUserId(userId)).thenReturn(Optional.of(state));service.accept(token,"SyntheticNew123!");assertThat(user.getAssignedRole()).isSameAs(role);assertThat(state.isSuspended()).isFalse();verifyNoInteractions(memberships);verify(suspensions).saveAndFlush(state);}
 @Test void expiredTokenCannotBeAccepted(){when(invitations.findById(hash)).thenReturn(Optional.of(invitation(Instant.now().minusSeconds(1))));assertThatThrownBy(()->service.accept(token,"SyntheticNew123!")).isInstanceOf(IllegalArgumentException.class);verifyNoInteractions(encoder,memberships);}
 @Test void changedRoleRequiresNewInvitation(){role.setPermissions(Set.of(UserPermission.USER_MANAGE));assertThatThrownBy(()->service.accept(token,"SyntheticNew123!")).isInstanceOf(IllegalArgumentException.class);verifyNoInteractions(encoder,memberships);}
 @Test void revokedIssuerOrChangedEmailBlocksAcceptance(){actor.setPlatformAdministrator(false);assertThatThrownBy(()->service.accept(token,"SyntheticNew123!")).isInstanceOf(IllegalArgumentException.class);actor.setPlatformAdministrator(true);user.setEmail("changed@example.invalid");assertThatThrownBy(()->service.accept(token,"SyntheticNew123!")).isInstanceOf(IllegalArgumentException.class);verifyNoInteractions(encoder,memberships);}
 @Test void changedCredentialStampAndAlreadyAcceptedIdentityCannotBeReused(){user.setPasswordHash("changed");assertThatThrownBy(()->service.accept(token,"SyntheticNew123!")).isInstanceOf(IllegalArgumentException.class);user.setPasswordHash("synthetic-hash");user.setInvitationPending(false);user.setActive(true);assertThatThrownBy(()->service.accept(token,"SyntheticNew123!")).isInstanceOf(IllegalArgumentException.class);verifyNoInteractions(encoder,memberships);}
 @Test void malformedSecretAndWeakPasswordNeverReachTokenStore(){assertThatThrownBy(()->service.accept("bad","SyntheticNew123!")).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->service.accept(token,"weak")).isInstanceOf(IllegalArgumentException.class);verify(invitations,never()).findById(any());}
}
