package de.corporate.lc.user.service;
import de.corporate.lc.user.api.*;import de.corporate.lc.user.domain.*;import de.corporate.lc.user.repository.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class UserService {
 private final AppUserRepository repo;private final AppRoleRepository roles;private final PasswordEncoder encoder;public UserService(AppUserRepository r,AppRoleRepository roles,PasswordEncoder e){repo=r;this.roles=roles;encoder=e;}
 public List<UserView> all(){return repo.findAllByOrderByUsernameAsc().stream().map(UserView::of).toList();}public List<AssignableUser> assignable(){return repo.findAllByActiveTrueOrderByDisplayNameAsc().stream().map(u->new AssignableUser(u.getUsername(),u.getDisplayName())).toList();}public boolean isAssignable(String username){return username!=null&&repo.findByUsernameIgnoreCase(username.trim()).filter(AppUser::isActive).isPresent();}
 @Transactional public UserView create(UserRequest r){String name=clean(r.username());if(repo.existsByUsernameIgnoreCase(name))throw new IllegalArgumentException("Benutzername existiert bereits.");validatePassword(r.password());AppUser u=new AppUser();apply(u,r,true);return UserView.of(repo.save(u));}
 @Transactional public UserView update(UUID id,UserRequest r,String current){AppUser u=one(id);if(repo.findByUsernameIgnoreCase(r.username()).filter(x->!x.getId().equals(id)).isPresent())throw new IllegalArgumentException("Benutzername existiert bereits.");AppRole role=role(r.roleId());boolean removesLastAdmin=u.getRole()==UserRole.ADMIN&&u.isActive()&&(role.getBaseRole()!=UserRole.ADMIN||!r.active())&&repo.countByRoleAndActiveTrue(UserRole.ADMIN)<=1;if(removesLastAdmin)throw new IllegalArgumentException("Der letzte aktive Administrator kann nicht deaktiviert oder herabgestuft werden.");if(u.getUsername().equalsIgnoreCase(current)&&!r.active())throw new IllegalArgumentException("Das eigene Konto kann nicht deaktiviert werden.");if(u.getUsername().equalsIgnoreCase(current)&&!role.getPermissions().contains(UserPermission.USER_MANAGE))throw new IllegalArgumentException("Die eigene Rolle muss die Benutzerverwaltung erlauben.");apply(u,r,false);return UserView.of(u);}
 @Transactional public void delete(UUID id,String current){AppUser u=one(id);if(u.getUsername().equalsIgnoreCase(current))throw new IllegalArgumentException("Das eigene Konto kann nicht gelöscht werden.");if(u.getRole()==UserRole.ADMIN&&u.isActive()&&repo.countByRoleAndActiveTrue(UserRole.ADMIN)<=1)throw new IllegalArgumentException("Der letzte aktive Administrator kann nicht gelöscht werden.");repo.delete(u);}
 @Transactional public void changePassword(String username,String currentPassword,String newPassword){AppUser u=repo.findByUsernameIgnoreCase(username).orElseThrow(()->new NoSuchElementException("Benutzer nicht gefunden"));if(!encoder.matches(currentPassword,u.getPasswordHash()))throw new IllegalArgumentException("Das aktuelle Passwort ist falsch.");validatePassword(newPassword);if(encoder.matches(newPassword,u.getPasswordHash()))throw new IllegalArgumentException("Das neue Passwort muss sich vom bisherigen unterscheiden.");u.setPasswordHash(encoder.encode(newPassword));}
 private void validatePassword(String password){if(password==null||password.length()<10)throw new IllegalArgumentException("Das Passwort muss mindestens 10 Zeichen lang sein.");if(!password.matches(".*[A-ZÄÖÜ].*")||!password.matches(".*[a-zäöüß].*")||!password.matches(".*\\d.*"))throw new IllegalArgumentException("Das Passwort muss Großbuchstaben, Kleinbuchstaben und eine Zahl enthalten.");}
 private void apply(AppUser u,UserRequest r,boolean creating){u.setEmail(UserEmail.required(r.email()));u.setUsername(clean(r.username()).toLowerCase(Locale.ROOT));u.setDisplayName(clean(r.displayName()));u.setAssignedRole(role(r.roleId()));u.setActive(r.active());if(r.password()!=null&&!r.password().isBlank()){validatePassword(r.password());u.setPasswordHash(encoder.encode(r.password()));}else if(creating)throw new IllegalArgumentException("Passwort fehlt.");}
 private AppRole role(UUID id){return roles.findById(id).orElseThrow(()->new NoSuchElementException("Rolle nicht gefunden"));}private AppUser one(UUID id){return repo.findById(id).orElseThrow(()->new NoSuchElementException("Benutzer nicht gefunden"));}private String clean(String v){return v==null?"":v.trim();}
}
