package de.corporate.lc.audit.service;
import de.corporate.lc.audit.domain.AuditEvent; import de.corporate.lc.audit.repository.AuditEventRepository;import de.corporate.lc.messaging.service.OutboxService; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import java.util.*;import java.nio.charset.StandardCharsets;
@Service public class AuditService {private final AuditEventRepository repo;private final OutboxService outbox;public AuditService(AuditEventRepository r,OutboxService outbox){repo=r;this.outbox=outbox;}public List<AuditEvent> recent(){return repo.findTop200ByOrderByOccurredAtDesc();}
 @Transactional(propagation=Propagation.REQUIRES_NEW)public void record(Authentication a,String action,String type,Object id,String details){record(a==null?"unbekannt":a.getName(),action,type,id,details,true,null);}
 @Transactional(propagation=Propagation.REQUIRES_NEW)public void recordChange(Authentication a,String action,String type,Object id,String details,String previousValue,String newValue){AuditEvent e=event(a==null?"unbekannt":a.getName(),action,type,id,details,true,null);e.setPreviousValue(clean(previousValue,4000,null));e.setNewValue(clean(newValue,4000,null));repo.save(e);enqueue(e);}
 @Transactional(propagation=Propagation.REQUIRES_NEW)public void record(String username,String action,String type,Object id,String details,boolean successful,String ip){AuditEvent e=new AuditEvent();e.setUsername(clean(username,100,"unbekannt"));e.setAction(clean(action,80,"UNKNOWN"));e.setEntityType(clean(type,80,null));e.setEntityId(id==null?null:clean(id.toString(),255,null));e.setDetails(clean(details,2000,null));e.setSuccessful(successful);e.setIpAddress(clean(ip,64,null));repo.save(e);enqueue(e);}
 public byte[] csv(){StringBuilder out=new StringBuilder("Zeitpunkt;Ergebnis;Benutzer;Aktion;Bereich;Objekt-ID;Details;Vorher;Nachher;IP-Adresse\n");for(AuditEvent e:recent()){cell(out,e.getOccurredAt());cell(out,e.isSuccessful()?"Erfolgreich":"Fehlgeschlagen");cell(out,e.getUsername());cell(out,e.getAction());cell(out,e.getEntityType());cell(out,e.getEntityId());cell(out,e.getDetails());cell(out,e.getPreviousValue());cell(out,e.getNewValue());cell(out,e.getIpAddress());out.setLength(out.length()-1);out.append('\n');}return ("\uFEFF"+out).getBytes(StandardCharsets.UTF_8);}
 @Transactional(propagation=Propagation.MANDATORY)public void recordInTransaction(Authentication a,String action,String type,Object id,String details){AuditEvent e=event(a==null?"unbekannt":a.getName(),action,type,id,details,true,null);repo.save(e);enqueue(e);}
 private AuditEvent event(String username,String action,String type,Object id,String details,boolean successful,String ip){AuditEvent e=new AuditEvent();e.setUsername(clean(username,100,"unbekannt"));e.setAction(clean(action,80,"UNKNOWN"));e.setEntityType(clean(type,80,null));e.setEntityId(id==null?null:clean(id.toString(),255,null));e.setDetails(clean(details,2000,null));e.setSuccessful(successful);e.setIpAddress(clean(ip,64,null));return e;}
 private void enqueue(AuditEvent e){String action=e.getAction();if(action==null||!(action.startsWith("LC_")||action.startsWith("DOCUMENT_")||action.startsWith("TRAINING_")||action.startsWith("SWIFT_")||action.startsWith("MT707_")||action.startsWith("EMAIL_")))return;Map<String,Object> payload=new LinkedHashMap<>();payload.put("action",action);payload.put("entityType",e.getEntityType());payload.put("entityId",e.getEntityId());payload.put("username",e.getUsername());payload.put("successful",e.isSuccessful());outbox.enqueue("corporate-lc."+action.toLowerCase(Locale.ROOT).replace('_','.'),e.getEntityId(),payload);}
 private void cell(StringBuilder out,Object value){String text=value==null?"":String.valueOf(value);out.append('"').append(text.replace("\"","\"\"")).append("\";");}
 private String clean(String v,int max,String fallback){if(v==null||v.isBlank())return fallback;String x=v.trim();return x.length()<=max?x:x.substring(0,max);}}
