package de.corporate.lc.user.api;
import de.corporate.lc.audit.service.AuditService;import de.corporate.lc.user.service.*;import jakarta.servlet.http.*;import org.springframework.http.*;import org.springframework.security.authentication.*;import org.springframework.security.core.*;import org.springframework.security.core.context.*;import org.springframework.security.core.userdetails.UserDetails;import org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler;import org.springframework.security.web.context.*;import org.springframework.security.web.csrf.CsrfToken;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/auth") public class AuthController {
 private static final String TOTP_PENDING_LOGIN="TOTP_PENDING_LOGIN",TOTP_PENDING_SECRET="TOTP_PENDING_SECRET";private final AuthenticationManager manager;private final UserService users;private final AppUserDetailsService details;private final TotpService totp;private final AuditService audit;private final SecurityContextRepository contexts=new HttpSessionSecurityContextRepository();
 public AuthController(AuthenticationManager manager,UserService users,AppUserDetailsService details,TotpService totp,AuditService audit){this.manager=manager;this.users=users;this.details=details;this.totp=totp;this.audit=audit;}public record LoginRequest(String username,String password){}public record TotpCodeRequest(String code){}public record TotpDisableRequest(String password,String code){}public record PasswordChangeRequest(String currentPassword,String newPassword){}
 @PostMapping("/login") public ResponseEntity<?> login(@RequestBody LoginRequest body,HttpServletRequest request,HttpServletResponse response){try{Authentication auth=manager.authenticate(UsernamePasswordAuthenticationToken.unauthenticated(body.username(),body.password()));if(totp.enabled(auth.getName())){request.getSession(true).setAttribute(TOTP_PENDING_LOGIN,auth.getName());audit.record(auth.getName(),"LOGIN_TOTP_REQUIRED","SESSION",null,"Passwort geprüft, zweiter Faktor angefordert",true,request.getRemoteAddr());return ResponseEntity.ok(Map.of("requiresTotp",true));}authenticate(auth,request,response);audit.record(auth.getName(),"LOGIN","SESSION",null,"Anmeldung erfolgreich",true,request.getRemoteAddr());return ResponseEntity.ok(Map.of("username",auth.getName(),"requiresTotp",false));}catch(org.springframework.security.core.AuthenticationException ex){audit.record(body.username(),"LOGIN","SESSION",null,"Anmeldung fehlgeschlagen",false,request.getRemoteAddr());return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("error","Benutzername oder Passwort ist falsch."));}}
 @PostMapping("/login/totp") public ResponseEntity<?> loginTotp(@RequestBody TotpCodeRequest body,HttpServletRequest request,HttpServletResponse response){HttpSession session=request.getSession(false);String username=session==null?null:(String)session.getAttribute(TOTP_PENDING_LOGIN);if(username==null)return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("error","Die Anmeldung ist abgelaufen. Bitte erneut anmelden."));if(!totp.verifyLogin(username,body.code())){audit.record(username,"LOGIN_TOTP_FAILED","SESSION",null,"Zweiter Faktor abgelehnt",false,request.getRemoteAddr());return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("error","TOTP- oder Notfallcode ist nicht gültig."));}UserDetails user=details.loadUserByUsername(username);Authentication auth=UsernamePasswordAuthenticationToken.authenticated(user,null,user.getAuthorities());authenticate(auth,request,response);session.removeAttribute(TOTP_PENDING_LOGIN);audit.record(username,"LOGIN","SESSION",null,"Anmeldung mit zweitem Faktor erfolgreich",true,request.getRemoteAddr());return ResponseEntity.ok(Map.of("username",username));}
 @GetMapping("/me") public Map<String,Object> me(Authentication auth,CsrfToken csrf){String role=auth.getAuthorities().stream().map(GrantedAuthority::getAuthority).filter(x->x.startsWith("ROLE_")).map(x->x.substring(5)).findFirst().orElse("USER");List<String> permissions=auth.getAuthorities().stream().map(GrantedAuthority::getAuthority).filter(x->x.startsWith("PERM_")).map(x->x.substring(5)).toList();return Map.of("username",auth.getName(),"role",role,"permissions",permissions,"csrfToken",csrf.getToken(),"totpEnabled",totp.enabled(auth.getName()));}
 @PostMapping("/totp/setup") public TotpService.Setup setupTotp(Authentication auth,HttpServletRequest request){TotpService.Setup setup=totp.setup(auth.getName());request.getSession(true).setAttribute(TOTP_PENDING_SECRET,setup.secret());audit.record(auth,"TOTP_SETUP_STARTED","USER",auth.getName(),"2FA-Einrichtung begonnen");return setup;}
 @PostMapping("/totp/enable") public Map<String,List<String>> enableTotp(@RequestBody TotpCodeRequest body,Authentication auth,HttpServletRequest request){String secret=(String)request.getSession(true).getAttribute(TOTP_PENDING_SECRET);if(secret==null)throw new IllegalStateException("Bitte die 2FA-Einrichtung erneut starten.");List<String> recovery=totp.enable(auth.getName(),secret,body.code());request.getSession().removeAttribute(TOTP_PENDING_SECRET);audit.record(auth,"TOTP_ENABLED","USER",auth.getName(),"Zwei-Faktor-Anmeldung aktiviert");return Map.of("recoveryCodes",recovery);}
 @PostMapping("/totp/disable") public ResponseEntity<Void> disableTotp(@RequestBody TotpDisableRequest body,Authentication auth){totp.disable(auth.getName(),body.password(),body.code());audit.record(auth,"TOTP_DISABLED","USER",auth.getName(),"Zwei-Faktor-Anmeldung deaktiviert");return ResponseEntity.noContent().build();}
 @PostMapping("/password") public ResponseEntity<Void> changePassword(@RequestBody PasswordChangeRequest body,Authentication auth){users.changePassword(auth.getName(),body.currentPassword(),body.newPassword());audit.record(auth,"PASSWORD_CHANGED","USER",auth.getName(),"Eigenes Passwort geändert");return ResponseEntity.noContent().build();}
 @PostMapping("/logout") public ResponseEntity<Void> logout(HttpServletRequest request,HttpServletResponse response,Authentication auth){audit.record(auth,"LOGOUT","SESSION",null,"Abmeldung");new SecurityContextLogoutHandler().logout(request,response,auth);return ResponseEntity.noContent().build();}
 private void authenticate(Authentication auth,HttpServletRequest request,HttpServletResponse response){SecurityContext context=SecurityContextHolder.createEmptyContext();context.setAuthentication(auth);SecurityContextHolder.setContext(context);contexts.saveContext(context,request,response);}
}
