package de.corporate.lc.user.api;
import de.corporate.lc.audit.service.AuditService;
import jakarta.servlet.http.*; import org.springframework.http.*; import org.springframework.security.authentication.*; import org.springframework.security.core.*; import org.springframework.security.core.context.*; import org.springframework.security.web.context.*; import org.springframework.security.web.csrf.CsrfToken; import org.springframework.web.bind.annotation.*; import java.util.Map;
@RestController @RequestMapping("/api/auth") public class AuthController {
 private final AuthenticationManager manager;private final de.corporate.lc.user.service.UserService users;private final AuditService audit;private final SecurityContextRepository contexts=new HttpSessionSecurityContextRepository();
 public AuthController(AuthenticationManager m,de.corporate.lc.user.service.UserService u,AuditService a){manager=m;users=u;audit=a;}
 public record LoginRequest(String username,String password){}
 public record PasswordChangeRequest(String currentPassword,String newPassword){}
 @PostMapping("/login") public ResponseEntity<?> login(@RequestBody LoginRequest r,HttpServletRequest request,HttpServletResponse response){try{Authentication auth=manager.authenticate(UsernamePasswordAuthenticationToken.unauthenticated(r.username(),r.password()));SecurityContext context=SecurityContextHolder.createEmptyContext();context.setAuthentication(auth);SecurityContextHolder.setContext(context);contexts.saveContext(context,request,response);audit.record(auth.getName(),"LOGIN","SESSION",null,"Anmeldung erfolgreich",true,request.getRemoteAddr());return ResponseEntity.ok(Map.of("username",auth.getName()));}catch(AuthenticationException ex){audit.record(r.username(),"LOGIN","SESSION",null,"Anmeldung fehlgeschlagen",false,request.getRemoteAddr());return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("error","Benutzername oder Passwort ist falsch."));}}
 @GetMapping("/me") public Map<String,Object> me(Authentication auth,CsrfToken csrf){String role=auth.getAuthorities().stream().map(GrantedAuthority::getAuthority).filter(x->x.startsWith("ROLE_")).map(x->x.substring(5)).findFirst().orElse("USER");return Map.of("username",auth.getName(),"role",role,"csrfToken",csrf.getToken());}
 @PostMapping("/password") public ResponseEntity<Void> changePassword(@RequestBody PasswordChangeRequest r,Authentication auth){users.changePassword(auth.getName(),r.currentPassword(),r.newPassword());audit.record(auth,"PASSWORD_CHANGED","USER",auth.getName(),"Eigenes Passwort geändert");return ResponseEntity.noContent().build();}
 @PostMapping("/logout") public ResponseEntity<Void> logout(HttpServletRequest request,HttpServletResponse response,Authentication auth){audit.record(auth,"LOGOUT","SESSION",null,"Abmeldung");new org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler().logout(request,response,auth);return ResponseEntity.noContent().build();}
}
