const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
async function fixture(state={}){const calls=[],section=node('section');let confirmed=true;function node(tag){return{tag,children:[],value:'',append(...items){this.children.push(...items)},replaceChildren(...items){this.children=items},setAttribute(){},reportValidity:()=>true,reset(){}};}const tenant={id:'other',code:'synthetic',name:'Synthetic tenant',active:true,bankEnabled:true,corporateEnabled:false,...state};const c=vm.createContext({document:{createElement:node},JSON,encodeURIComponent,renderTenantInventory:(panel,preview)=>{panel.textContent='Inventory '+preview.tenantId;},location:{reload(){}},LcSelectedTenantId:'current',confirmAction:async()=>confirmed,json:async(url,options)=>{calls.push({url,options});if(options?.method)return{};if(url.endsWith('/inventory'))return {tenantId:'other'};return[{id:'current',code:'default',name:'Default',active:true,bankEnabled:true,corporateEnabled:true},tenant];}});vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../main/resources/static/platform-tenants.js'),'utf8'),c);const refresh=await c.setupPlatformTenants(section);return{section,calls,refresh,setConfirm:v=>confirmed=v};}
function all(n){return[n,...n.children.flatMap(all)];}
test('full deletion requires exact code, both acknowledgements and final confirmation',async()=>{
 const f=await fixture({active:false,archived:true});await f.refresh();
 const row=all(f.section).find(n=>n.tag==='article'&&n.children.some(c=>c.textContent==='Synthetic tenant · synthetic'));
 const deletion=row.children.find(n=>n.tag==='details'),inputs=all(deletion).filter(n=>n.tag==='input'),button=all(deletion).find(n=>n.textContent==='Delete permanently');
 await button.onclick();assert.equal(f.calls.some(c=>c.options?.method==='DELETE'),false);
 inputs[0].value='synthetic';inputs[1].checked=true;inputs[2].checked=true;f.setConfirm(false);await button.onclick();assert.equal(f.calls.some(c=>c.options?.method==='DELETE'),false);
 f.setConfirm(true);await button.onclick();const request=f.calls.find(c=>c.options?.method==='DELETE');assert.equal(request.url,'/api/platform/tenants/other');assert.deepEqual(JSON.parse(request.options.body),{tenantCode:'synthetic',deleteAllBusinessData:true,acknowledgeAuditAndBackupsRetained:true});
});
test('central tenant form waits for the platform page, creates explicit profile and language',async()=>{const f=await fixture();assert.equal(f.calls.length,0);const form=all(f.section).find(n=>n.tag==='form'),fields=all(form).filter(n=>n.tag==='input'),selects=all(form).filter(n=>n.tag==='select');fields[0].value='synthetic';fields[1].value='Synthetic';selects[0].value='en';selects[1].value='corporate';await form.onsubmit({preventDefault(){}});const call=f.calls.find(c=>c.options?.method==='POST');assert.equal(call.url,'/api/platform/tenants');assert.deepEqual(JSON.parse(call.options.body),{code:'synthetic',name:'Synthetic',defaultLanguage:'en',bankEnabled:false,corporateEnabled:true});});
test('suspension protects current tenant and confirms data preservation before updating',async()=>{const f=await fixture();await f.refresh();let buttons=all(f.section).filter(n=>n.textContent==='Suspend tenant');assert.equal(buttons[0].disabled,true);assert.equal(buttons[1].disabled,false);f.setConfirm(false);await buttons[1].onclick();assert.equal(f.calls.some(c=>c.options?.method==='PUT'),false);f.setConfirm(true);await buttons[1].onclick();const request=f.calls.find(c=>c.options?.method==='PUT');assert.equal(request.url,'/api/platform/tenants/other');assert.deepEqual(JSON.parse(request.options.body),{active:false,bankEnabled:true,corporateEnabled:false});});

test('inventory loads only on request using GET and renders inline, without dialog or mutation',async()=>{const f=await fixture();await f.refresh();assert.equal(f.calls.some(c=>c.url.endsWith('/inventory')),false);const buttons=all(f.section).filter(n=>n.textContent==='Inventory / deletion preview');await buttons[1].onclick();const request=f.calls.find(c=>c.url.endsWith('/inventory'));assert.equal(request.url,'/api/platform/tenants/other/inventory');assert.equal(request.options,undefined);assert.ok(all(f.section).some(n=>n.textContent==='Inventory other'&&n.hidden===false));assert.equal(all(f.section).some(n=>n.tag==='dialog'),false);});

test('archival requires suspension and confirmation; restore uses distinct action',async()=>{const f=await fixture({active:false});await f.refresh();const archive=all(f.section).filter(n=>n.textContent==='Archive tenant')[1];assert.equal(archive.disabled,false);f.setConfirm(false);await archive.onclick();assert.equal(f.calls.some(c=>c.url.endsWith('/archive')),false);f.setConfirm(true);await archive.onclick();const request=f.calls.find(c=>c.url.endsWith('/archive'));assert.deepEqual(JSON.parse(request.options.body),{archived:true});const a=await fixture({active:false,archived:true});await a.refresh();assert.equal(all(a.section).find(n=>n.textContent==='Activate tenant').disabled,true);await all(a.section).find(n=>n.textContent==='Restore archive').onclick();assert.deepEqual(JSON.parse(a.calls.find(c=>c.url.endsWith('/archive')).options.body),{archived:false});});
