const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
async function fixture(enabled=true){
 const nodes=new Map(),calls=[],pages=[];let confirmation=true,fail=false,active=true;
 function node(tag){let id='';const n={tag,dataset:{},children:[],textContent:'',append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;},setAttribute(k,v){this[k]=v;}};Object.defineProperty(n,'id',{get:()=>id,set:v=>{id=v;nodes.set('#'+v,n);}});return n;}
 const nav=node('nav'),main=node('main');nodes.set('#appNav nav',nav);nodes.set('main',main);
 const accounts=()=>[{id:'own',username:'admin',displayName:'Own',email:'admin@example.invalid',active:true,platformAdministrator:true},{id:'other',username:'<script>untrusted',displayName:'Synthetic other',email:'other@example.invalid',active,platformAdministrator:false}];
 const context=vm.createContext({document:{querySelector:s=>nodes.get(s),createElement:node},currentUser:{username:'admin'},encodeURIComponent,JSON,appNavigate:(...args)=>pages.push(args),confirmAction:async()=>confirmation,json:async(url,options)=>{calls.push({url,options});if(url==='/api/platform/access')return{enabled};if(options?.method==='PUT'){if(fail)throw Error('Synthetic rejection');active=JSON.parse(options.body).active;return{};}return accounts();}});
 vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../main/resources/static/platform-admin.js'),'utf8'),context);await context.setupPlatformAdministration();
 return{nodes,nav,main,calls,pages,setConfirmation:v=>confirmation=v,setFailure:v=>fail=v};
}
function descendants(n){return[n,...n.children.flatMap(descendants)];}
test('platform page is not created for a local administrator without a global grant',async()=>{const f=await fixture(false);assert.equal(f.nodes.has('#appNavPlatform'),false);assert.equal(f.calls.length,1);});
test('menu opens a page before loading accounts, with escaped identity data and protected self-access',async()=>{const f=await fixture();assert.equal(f.pages.length,0);assert.equal(f.calls.length,1);await f.nodes.get('#appNavPlatform').onclick();assert.equal(f.pages[0][0],'platform');const elements=descendants(f.main);const name=elements.find(n=>n.textContent==='<script>untrusted');assert.equal(name.innerHTML,undefined);const toggles=elements.filter(n=>n.tag==='button'&&n.textContent==='Suspend global account');assert.equal(toggles[0].disabled,true);assert.equal(toggles[1].disabled,false);});
test('global suspension requires confirmation and sends only active with JSON',async()=>{const f=await fixture();await f.nodes.get('#appNavPlatform').onclick();const button=descendants(f.main).filter(n=>n.tag==='button'&&n.textContent==='Suspend global account')[1];f.setConfirmation(false);await button.onclick();assert.equal(f.calls.some(c=>c.options?.method==='PUT'),false);f.setConfirmation(true);await button.onclick();const request=f.calls.find(c=>c.options?.method==='PUT');assert.equal(request.url,'/api/platform/users/other/access');assert.deepEqual(JSON.parse(request.options.body),{active:false});assert.equal(request.options.headers['Content-Type'],'application/json');assert.ok(descendants(f.main).some(n=>n.textContent==='Globally suspended'));});
test('rejected access update leaves action retryable and reports server error',async()=>{const f=await fixture();await f.nodes.get('#appNavPlatform').onclick();const button=descendants(f.main).filter(n=>n.tag==='button'&&n.textContent==='Suspend global account')[1];f.setFailure(true);await button.onclick();assert.equal(button.disabled,false);assert.ok(descendants(f.main).some(n=>n.textContent==='Synthetic rejection'));});
