const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
async function fixture(enabled=true,pending=[],standalone=true){
 const nodes=new Map(),calls=[],pages=[];let confirmation=true,fail=false,active=true;
 function node(tag){let id='';const n={tag,classList:{remove(){}},dataset:{},children:[],textContent:'',value:'',reportValidity:()=>true,reset(){for(const n of descendants(this))if(n.tag==='input')n.value='';},append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;},setAttribute(k,v){this[k]=v;}};Object.defineProperty(n,'id',{get:()=>id,set:v=>{id=v;nodes.set('#'+v,n);}});return n;}
 const nav=node('nav'),main=node('main');nodes.set('#appNav nav',nav);nodes.set('main',main);
 const accounts=()=>[{id:'own',username:'admin',displayName:'Own',email:'admin@example.invalid',active:true,platformAdministrator:true,totpEnabled:true},{id:'other',username:'<script>untrusted',displayName:'Synthetic other',email:'other@example.invalid',active,platformAdministrator:false,totpEnabled:true}];
 const context=vm.createContext({document:{querySelector:s=>nodes.get(s),createElement:node},setupPlatformTenants:async()=>async()=>{},currentUser:{username:'admin'},encodeURIComponent,JSON,appNavigate:(...args)=>pages.push(args),confirmAction:async()=>confirmation,json:async(url,options)=>{calls.push({url,options});if(url==='/api/platform/access')return{enabled};if(options?.method==='POST'){if(fail)throw Error('Synthetic rejection');return{};}if(options?.method==='PUT'){if(fail)throw Error('Synthetic rejection');if(url.endsWith('/access'))active=JSON.parse(options.body).active;return{};}if(url.endsWith('/choices'))return[{id:'tenant',name:'Synthetic tenant',code:'synthetic',roles:[{id:'role',name:'Viewer',permissions:[]}]}];if(url==='/api/platform/invitations')return pending;return accounts();}});
 context.location={assign:url=>pages.push(url)};
 vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../main/resources/static/platform-admin.js'),'utf8'),context);await context.setupPlatformAdministration(standalone);
 return{nodes,nav,main,calls,pages,setConfirmation:v=>confirmation=v,setFailure:v=>fail=v};
}
function descendants(n){return[n,...n.children.flatMap(descendants)];}
test('workspace menu navigates to the separate global page without rendering global data',async()=>{
 const f=await fixture(true,[],false);assert.equal(f.main.children.length,0);assert.equal(f.calls.length,1);
 await f.nodes.get('#appNavPlatform').onclick();assert.deepEqual(f.pages,['/platform.html']);assert.equal(f.calls.length,1);
});
test('platform page is not created for a local administrator without a global grant',async()=>{const f=await fixture(false);assert.equal(f.nodes.has('#appNavPlatform'),false);assert.equal(f.calls.length,1);});
test('menu opens a page before loading accounts, with escaped identity data and protected self-access',async()=>{const f=await fixture();assert.equal(f.pages.length,0);assert.equal(f.calls.length,1);await f.nodes.get('#appNavPlatform').onclick();assert.equal(f.pages.length,0);const elements=descendants(f.main);const name=elements.find(n=>n.textContent==='<script>untrusted');assert.equal(name.innerHTML,undefined);const toggles=elements.filter(n=>n.tag==='button'&&n.textContent==='Suspend global account');assert.equal(toggles[0].disabled,true);assert.equal(toggles[1].disabled,false);});
test('global suspension requires confirmation and sends only active with JSON',async()=>{const f=await fixture();await f.nodes.get('#appNavPlatform').onclick();const button=descendants(f.main).filter(n=>n.tag==='button'&&n.textContent==='Suspend global account')[1];f.setConfirmation(false);await button.onclick();assert.equal(f.calls.some(c=>c.options?.method==='PUT'),false);f.setConfirmation(true);await button.onclick();const request=f.calls.find(c=>c.options?.method==='PUT');assert.equal(request.url,'/api/platform/users/other/access');assert.deepEqual(JSON.parse(request.options.body),{active:false});assert.equal(request.options.headers['Content-Type'],'application/json');assert.ok(descendants(f.main).some(n=>n.textContent==='Globally suspended'));});
test('rejected access update leaves action retryable and reports server error',async()=>{const f=await fixture();await f.nodes.get('#appNavPlatform').onclick();const button=descendants(f.main).filter(n=>n.tag==='button'&&n.textContent==='Suspend global account')[1];f.setFailure(true);await button.onclick();assert.equal(button.disabled,false);assert.ok(descendants(f.main).some(n=>n.textContent==='Synthetic rejection'));});
test('invitation sends explicit tenant and role but no password or platform grant',async()=>{const f=await fixture();await f.nodes.get('#appNavPlatform').onclick();assert.equal(f.nodes.get('#platformCreatetenantId').value,'');for(const [key,value] of Object.entries({username:'new',displayName:'New',email:'new@example.invalid',tenantId:'tenant',roleId:'role'}))f.nodes.get('#platformCreate'+key).value=value;await descendants(f.main).find(n=>n.tag==='form').onsubmit({preventDefault(){}});const call=f.calls.find(c=>c.options?.method==='POST');assert.equal(call.url,'/api/platform/invitations');assert.deepEqual(JSON.parse(call.options.body),{username:'new',displayName:'New',email:'new@example.invalid',tenantId:'tenant',roleId:'role'});assert.equal(f.nodes.has('#platformCreatepassword'),false);});
test('failed invitation retains identity for retry',async()=>{const f=await fixture();await f.nodes.get('#appNavPlatform').onclick();f.nodes.get('#platformCreateusername').value='new';f.setFailure(true);await descendants(f.main).find(n=>n.tag==='form').onsubmit({preventDefault(){}});assert.equal(f.nodes.get('#platformCreateusername').value,'new');assert.equal(descendants(f.main).find(n=>n.type==='submit').disabled,false);});
test('platform grant requires confirmation and uses a separate boolean-only endpoint',async()=>{const f=await fixture();await f.nodes.get('#appNavPlatform').onclick();const elements=descendants(f.main),own=elements.find(n=>n.textContent==='Revoke platform rights');assert.equal(own.disabled,true);const grant=elements.find(n=>n.textContent==='Grant platform rights');f.setConfirmation(false);await grant.onclick();assert.equal(f.calls.some(c=>c.url.endsWith('/platform-grant')),false);f.setConfirmation(true);await grant.onclick();const call=f.calls.find(c=>c.url.endsWith('/platform-grant'));assert.deepEqual(JSON.parse(call.options.body),{granted:true});});

test('invitation queue exposes safe attempts and next retry without rendering server details',async()=>{const f=await fixture(true,[{userId:'pending',username:'Queued',tenantName:'Synthetic',roleName:'Viewer',status:'MAIL_RETRY',attempts:2,nextAttemptAt:'2026-10-08T12:00:00Z',expiresAt:'2026-10-09T12:00:00Z',errorCode:'SMTP_FAILED',encryptedMailPayload:'MUST_NOT_RENDER'}]);await f.nodes.get('#appNavPlatform').onclick();const values=descendants(f.main).map(n=>n.textContent).join(' ');assert.match(values,/Attempts: 2/);assert.match(values,/Next attempt:/);assert.doesNotMatch(values,/MUST_NOT_RENDER/);});
