const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.resolve(__dirname,'../../main/resources/static/tenants.js'),'utf8');
async function fixture(enabled=true,allowed=false,failReadiness=false){
 const nodes=new Map(),calls=[],pages=[],confirmations=[];let reloads=0,failSwitch=false,confirm=async()=>true,requestHook;
 function node(tag){let id='';const n={tag,children:[],dataset:{},textContent:'',append(...children){this.children.push(...children);},prepend(...children){this.children.unshift(...children);},replaceChildren(...children){this.children=children;},setAttribute(k,v){this[k]=v;},reset(){}};Object.defineProperty(n,'id',{get:()=>id,set:value=>{id=value;nodes.set(value,n);}});return n;}
 const nav=node('nav'),main=node('main'),header=node('header');
 const overview={selectedTenantId:'home',creationEnabled:enabled,workspaces:[{id:'home',name:'Home',code:'home'},{id:'other',name:'<script>untrusted</script>',code:'other'}]};
const context=vm.createContext({confirmAction:async(message,labels)=>{confirmations.push({message,labels});return confirm();},can:()=>allowed,document:{createElement:node,querySelector:s=>s==='#appNav nav'?nav:s==='main'?main:header},appNavigate:(...args)=>pages.push(args),json:async(url,options)=>{calls.push({url,options});if(requestHook){const intercepted=requestHook(url,options);if(intercepted!==undefined)return intercepted;}if(url==='/api/tenants'&&!options)return overview;if(url==='/api/tenants/current/settings'&&!options)return {name:'Synthetic workspace',defaultLanguage:'en',editingEnabled:enabled};if(url==='/api/tenants/current/readiness'){if(failReadiness)throw Error('Setup unavailable');return {companies:0,templates:2,activeMembers:1};}if(url.endsWith('/select')){if(failSwitch)throw Error('No active membership');return {}; }if(url==='/api/tenants'&&options?.method==='POST'){const created={id:'created',name:'Synthetic created',code:'synthetic'};overview.workspaces.push(created);return created;}return {};},location:{reload:()=>reloads++},encodeURIComponent,JSON,Object,FormData:class{constructor(){return new Map([['code','synthetic'],['name','Synthetic'],['defaultLanguage','en']]);}}});
 vm.runInContext(source,context);await context.setupTenants();
 return {nodes,nav,main,header,calls,pages,context,confirmations,setRequestHook:fn=>requestHook=fn,setConfirm:fn=>confirm=fn,get reloads(){return reloads;},setFailSwitch:()=>failSwitch=true};
}
function descendants(node){return[node,...node.children.flatMap(descendants)];}
test('failed tenant loading exposes retry and success clears old error',async()=>{const f=await fixture();f.setRequestHook(url=>{if(url==='/api/tenants')return Promise.reject(Error('Tenant unavailable'));});await f.nodes.get('appNavTenants').onclick();assert.equal(f.nodes.get('tenantRetry').hidden,false);assert.equal(f.nodes.get('tenantSection')['aria-busy'],'false');assert.ok(descendants(f.main).some(n=>n.textContent==='Tenant unavailable'));f.setRequestHook(undefined);await f.nodes.get('tenantRetry').onclick();assert.equal(f.nodes.get('tenantRetry').hidden,true);assert.equal(descendants(f.header).find(n=>n.tag==='select').disabled,false);assert.equal(descendants(f.main).some(n=>n.textContent==='Tenant unavailable'),false);});
test('older completion cannot clear latest loading state',async()=>{const f=await fixture();let count=0,resolveFirst,resolveSecond;f.setRequestHook(url=>{if(url==='/api/tenants'){count++;return new Promise(resolve=>{if(count===1)resolveFirst=resolve;else resolveSecond=resolve;});}});const first=f.nodes.get('appNavTenants').onclick(),second=f.nodes.get('appNavTenants').onclick();const overview={selectedTenantId:'home',creationEnabled:true,workspaces:[{id:'home',name:'Home',code:'home'}]};resolveFirst(overview);await first;assert.equal(f.nodes.get('tenantSection')['aria-busy'],'true');assert.ok(descendants(f.main).some(n=>n.textContent==='Loading tenant information…'));resolveSecond(overview);await second;assert.equal(f.nodes.get('tenantSection')['aria-busy'],'false');assert.equal(descendants(f.main).some(n=>n.textContent==='Loading tenant information…'),false);});
test('late overview cannot replace a newer refresh',async()=>{const f=await fixture();let resolve,first=true;f.setRequestHook(url=>{if(url==='/api/tenants'&&first){first=false;return new Promise(r=>resolve=r);}});const old=f.nodes.get('appNavTenants').onclick();await f.nodes.get('appNavTenants').onclick();resolve({selectedTenantId:'old',creationEnabled:false,workspaces:[{id:'old',name:'Stale workspace',code:'old'}]});await old;assert.equal(descendants(f.header).find(n=>n.tag==='select').value,'home');assert.equal(descendants(f.nodes.get('tenantLoginInfo')).some(n=>n.textContent==='Stale workspace'),false);});
test('late settings cannot overwrite newer editable fields',async()=>{const f=await fixture();let resolve,signal,first=true;const started=new Promise(r=>signal=r);f.setRequestHook(url=>{if(url==='/api/tenants/current/settings'&&first){first=false;signal();return new Promise(r=>resolve=r);}});const old=f.nodes.get('appNavTenants').onclick();await started;await f.nodes.get('appNavTenants').onclick();resolve({name:'Stale settings',defaultLanguage:'de',editingEnabled:false});await old;const form=f.nodes.get('tenantSettingsForm');assert.equal(form.hidden,false);assert.equal(descendants(form).find(n=>n.name==='name').value,'Synthetic workspace');});
test('stale setup response and stale failure leave newest page intact',async()=>{for(const fail of [false,true]){const f=await fixture(true,true);let settle,signal,first=true;const started=new Promise(r=>signal=r);f.setRequestHook(url=>{if(url==='/api/tenants/current/readiness'&&first){first=false;signal();return new Promise((resolve,reject)=>settle=fail?reject:resolve);}});const old=f.nodes.get('appNavTenants').onclick();await started;await f.nodes.get('appNavTenants').onclick();settle(fail?Error('Stale failure'):{companies:99,templates:99,activeMembers:99});await old;const labels=descendants(f.nodes.get('tenantReadiness')).map(n=>n.textContent).join(' ');assert.match(labels,/Present · 2/);assert.doesNotMatch(labels,/99|Stale failure/);}});
test('stale overview failure cannot disable newer successful selection',async()=>{const f=await fixture();let reject,first=true;f.setRequestHook(url=>{if(url==='/api/tenants'&&first){first=false;return new Promise((_,r)=>reject=r);}});const old=f.nodes.get('appNavTenants').onclick();await f.nodes.get('appNavTenants').onclick();reject(Error('Old failure'));await old;assert.equal(descendants(f.header).find(n=>n.tag==='select').disabled,false);assert.equal(f.nodes.get('tenantSettingsForm').hidden,false);});
test('creation offers explicit confirmed opening without automatically switching',async()=>{const f=await fixture(),form=descendants(f.main).find(n=>n.tag==='form');assert.equal(f.nodes.get('tenantCreatedInfo').hidden,true);await form.onsubmit({preventDefault(){}});assert.equal(f.reloads,0);assert.equal(f.confirmations.length,0);const panel=f.nodes.get('tenantCreatedInfo');assert.equal(panel.hidden,false);assert.match(descendants(panel).map(n=>n.textContent).join(' '),/Existing business data is not copied/);await f.nodes.get('tenantCreatedOpen').onclick();assert.equal(f.confirmations.length,1);assert.ok(f.calls.some(c=>c.url==='/api/tenants/created/select'));assert.equal(f.reloads,1);});
test('cancelling opening a newly created tenant keeps the current workspace',async()=>{const f=await fixture(),form=descendants(f.main).find(n=>n.tag==='form');await form.onsubmit({preventDefault(){}});f.setConfirm(async()=>false);await f.nodes.get('tenantCreatedOpen').onclick();assert.equal(f.reloads,0);assert.equal(f.calls.some(c=>c.url.endsWith('/select')),false);assert.equal(f.nodes.get('tenantCreatedInfo').hidden,false);});
test('cancelled switch preserves workspace and sends no request',async()=>{const f=await fixture();f.setConfirm(async()=>false);const chooser=descendants(f.header).find(n=>n.tag==='select');chooser.value='other';await chooser.onchange();assert.equal(chooser.value,'home');assert.equal(chooser.disabled,false);assert.equal(f.reloads,0);assert.equal(f.calls.some(c=>c.options?.method==='POST'),false);assert.match(f.confirmations[0].message,/Unsaved changes may be lost/);assert.match(f.confirmations[0].message,/<script>untrusted<\/script> \(other\)/);assert.equal(f.confirmations[0].labels.cancel,'Stay here');});
test('pending confirmation suppresses duplicate workspace switches',async()=>{const f=await fixture();let finish;f.setConfirm(()=>new Promise(resolve=>finish=resolve));const chooser=descendants(f.header).find(n=>n.tag==='select');chooser.value='other';const pending=chooser.onchange();await chooser.onchange();assert.equal(f.confirmations.length,1);assert.equal(chooser.disabled,true);assert.equal(f.calls.some(c=>c.options?.method==='POST'),false);finish(true);await pending;assert.equal(f.calls.filter(c=>c.url.endsWith('/select')).length,1);assert.equal(f.reloads,1);});
test('unknown and already selected workspaces cannot trigger a switch',async()=>{const f=await fixture(),chooser=descendants(f.header).find(n=>n.tag==='select');chooser.value='missing';await chooser.onchange();assert.equal(chooser.value,'home');await chooser.onchange();assert.equal(f.confirmations.length,0);assert.equal(f.calls.some(c=>c.options?.method==='POST'),false);});
test('confirmation failure restores selector and permits retry',async()=>{const f=await fixture(),chooser=descendants(f.header).find(n=>n.tag==='select');f.setConfirm(async()=>{throw Error('Confirmation unavailable');});chooser.value='other';await chooser.onchange();assert.equal(chooser.value,'home');assert.equal(chooser.disabled,false);assert.equal(f.reloads,0);f.setConfirm(async()=>true);chooser.value='other';await chooser.onchange();assert.equal(f.reloads,1);});
test('read-only members see selected tenant login guidance without administrative counts',async()=>{const f=await fixture(false,false),panel=f.nodes.get('tenantLoginInfo');assert.equal(panel.hidden,false);const labels=descendants(panel).map(n=>n.textContent).join(' ');assert.match(labels,/Tenant code for login: home/);assert.match(labels,/Leaving the tenant field blank opens the default tenant/);assert.match(labels,/does not grant access/);assert.equal(f.calls.some(c=>c.url==='/api/tenants/current/readiness'),false);assert.equal(descendants(panel).some(n=>n.tag==='form'||n.tag==='input'),false);});
test('login guidance displays only the selected workspace, using text rather than HTML',async()=>{const f=await fixture(),panel=f.nodes.get('tenantLoginInfo');assert.equal(descendants(panel).some(n=>n.textContent.includes('untrusted')),false);assert.ok(descendants(panel).every(n=>n.innerHTML===undefined));});
test('setup summary uses current tenant endpoint and reports presence counts',async()=>{const f=await fixture(true,true),panel=f.nodes.get('tenantReadiness');assert.equal(panel.hidden,false);assert.ok(f.calls.some(c=>c.url==='/api/tenants/current/readiness'));const labels=descendants(panel).map(n=>n.textContent).join(' ');assert.match(labels,/Not yet configured · 0/);assert.match(labels,/Present · 2/);assert.match(labels,/Presence checks only/);assert.equal(descendants(panel).filter(n=>n.tag==='button').length,3);});
test('setup counts are not requested without administration permissions',async()=>{const f=await fixture(true,false);assert.equal(f.nodes.get('tenantReadiness').hidden,true);assert.equal(f.calls.some(c=>c.url==='/api/tenants/current/readiness'),false);});
test('setup failure does not hide working tenant selection or settings',async()=>{const f=await fixture(true,true,true);assert.equal(f.nodes.get('tenantSettingsForm').hidden,false);assert.ok(descendants(f.nodes.get('tenantReadiness')).some(n=>n.textContent==='Setup unavailable'));assert.equal(descendants(f.header).find(n=>n.tag==='select').disabled,false);});
test('tenant menu opens a page and names cannot inject markup',async()=>{const f=await fixture();assert.equal(f.pages.length,0);f.nodes.get('appNavTenants').onclick();assert.equal(f.pages[0][0],'tenants');const names=descendants(f.main).filter(n=>n.textContent.includes('untrusted'));assert.ok(names.length);assert.ok(names.every(n=>n.innerHTML===undefined));});
test('creation sends explicit JSON and remains hidden without rights',async()=>{const f=await fixture();const form=descendants(f.main).find(n=>n.tag==='form');await form.onsubmit({preventDefault(){}});const request=f.calls.find(c=>c.options?.method==='POST');assert.equal(request.url,'/api/tenants');assert.equal(request.options.headers['Content-Type'],'application/json');assert.deepEqual(JSON.parse(request.options.body),{code:'synthetic',name:'Synthetic',defaultLanguage:'en',bankEnabled:true,corporateEnabled:false});const readonly=await fixture(false);const disabled=descendants(readonly.main).find(n=>n.tag==='form');assert.equal(disabled.hidden,true);await disabled.onsubmit({preventDefault(){}});assert.equal(readonly.calls.some(c=>c.options?.method==='POST'),false);});
test('workspace selection reloads to discard stale case state',async()=>{const f=await fixture();const chooser=descendants(f.header).find(n=>n.tag==='select');chooser.value='other';await chooser.onchange();const request=f.calls.find(c=>c.options?.method==='POST');assert.equal(request.url,'/api/tenants/other/select');assert.equal(f.reloads,1);});
test('failed selection keeps old workspace and shows readable error',async()=>{const f=await fixture();f.setFailSwitch();const chooser=descendants(f.header).find(n=>n.tag==='select');chooser.value='other';await chooser.onchange();assert.equal(chooser.value,'home');assert.equal(f.reloads,0);assert.ok(descendants(f.main).some(n=>n.textContent==='No active membership'));});
test('settings remain hidden and cannot submit without editing permission',async()=>{const f=await fixture(false),form=f.nodes.get('tenantSettingsForm');assert.equal(form.hidden,true);await form.onsubmit({preventDefault(){}});assert.equal(f.calls.some(c=>c.options?.method==='PUT'),false);});
test('settings update sends only name and language to the current tenant endpoint',async()=>{const f=await fixture(),form=f.nodes.get('tenantSettingsForm');assert.equal(form.hidden,false);const fields=descendants(form);fields.find(n=>n.name==='name').value='Renamed synthetic';fields.find(n=>n.name==='defaultLanguage').value='de';await form.onsubmit({preventDefault(){}});const request=f.calls.find(c=>c.options?.method==='PUT');assert.equal(request.url,'/api/tenants/current/settings');assert.equal(request.options.headers['Content-Type'],'application/json');assert.deepEqual(JSON.parse(request.options.body),{name:'Renamed synthetic',defaultLanguage:'de'});});
