const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.resolve(__dirname,'../../main/resources/static/tenants.js'),'utf8');
async function fixture(enabled=true){
 const nodes=new Map(),calls=[],pages=[];let reloads=0,failSwitch=false;
 function node(tag){let id='';const n={tag,children:[],dataset:{},textContent:'',append(...children){this.children.push(...children);},prepend(...children){this.children.unshift(...children);},replaceChildren(...children){this.children=children;},setAttribute(k,v){this[k]=v;},reset(){}};Object.defineProperty(n,'id',{get:()=>id,set:value=>{id=value;nodes.set(value,n);}});return n;}
 const nav=node('nav'),main=node('main'),header=node('header');
 const overview={selectedTenantId:'home',creationEnabled:enabled,workspaces:[{id:'home',name:'Home',code:'home'},{id:'other',name:'<script>untrusted</script>',code:'other'}]};
const context=vm.createContext({document:{createElement:node,querySelector:s=>s==='#appNav nav'?nav:s==='main'?main:header},appNavigate:(...args)=>pages.push(args),json:async(url,options)=>{calls.push({url,options});if(url==='/api/tenants'&&!options)return overview;if(url==='/api/tenants/current/settings'&&!options)return {name:'Synthetic workspace',defaultLanguage:'en',editingEnabled:enabled};if(url.endsWith('/select')){if(failSwitch)throw Error('No active membership');return {}; }return {id:'created',name:'Synthetic created'};},location:{reload:()=>reloads++},encodeURIComponent,JSON,Object,FormData:class{constructor(){return new Map([['code','synthetic'],['name','Synthetic'],['defaultLanguage','en']]);}}});
 vm.runInContext(source,context);await context.setupTenants();
 return {nodes,nav,main,header,calls,pages,context,get reloads(){return reloads;},setFailSwitch:()=>failSwitch=true};
}
function descendants(node){return[node,...node.children.flatMap(descendants)];}
test('tenant menu opens a page and names cannot inject markup',async()=>{const f=await fixture();assert.equal(f.pages.length,0);f.nodes.get('appNavTenants').onclick();assert.equal(f.pages[0][0],'tenants');const names=descendants(f.main).filter(n=>n.textContent.includes('untrusted'));assert.ok(names.length);assert.ok(names.every(n=>n.innerHTML===undefined));});
test('creation sends explicit JSON and remains hidden without rights',async()=>{const f=await fixture();const form=descendants(f.main).find(n=>n.tag==='form');await form.onsubmit({preventDefault(){}});const request=f.calls.find(c=>c.options?.method==='POST');assert.equal(request.url,'/api/tenants');assert.equal(request.options.headers['Content-Type'],'application/json');assert.deepEqual(JSON.parse(request.options.body),{code:'synthetic',name:'Synthetic',defaultLanguage:'en',bankEnabled:true,corporateEnabled:false});const readonly=await fixture(false);const disabled=descendants(readonly.main).find(n=>n.tag==='form');assert.equal(disabled.hidden,true);await disabled.onsubmit({preventDefault(){}});assert.equal(readonly.calls.some(c=>c.options?.method==='POST'),false);});
test('workspace selection reloads to discard stale case state',async()=>{const f=await fixture();const chooser=descendants(f.header).find(n=>n.tag==='select');chooser.value='other';await chooser.onchange();const request=f.calls.find(c=>c.options?.method==='POST');assert.equal(request.url,'/api/tenants/other/select');assert.equal(f.reloads,1);});
test('failed selection keeps old workspace and shows readable error',async()=>{const f=await fixture();f.setFailSwitch();const chooser=descendants(f.header).find(n=>n.tag==='select');chooser.value='other';await chooser.onchange();assert.equal(chooser.value,'home');assert.equal(f.reloads,0);assert.ok(descendants(f.main).some(n=>n.textContent==='No active membership'));});
test('settings remain hidden and cannot submit without editing permission',async()=>{const f=await fixture(false),form=f.nodes.get('tenantSettingsForm');assert.equal(form.hidden,true);await form.onsubmit({preventDefault(){}});assert.equal(f.calls.some(c=>c.options?.method==='PUT'),false);});
test('settings update sends only name and language to the current tenant endpoint',async()=>{const f=await fixture(),form=f.nodes.get('tenantSettingsForm');assert.equal(form.hidden,false);const fields=descendants(form);fields.find(n=>n.name==='name').value='Renamed synthetic';fields.find(n=>n.name==='defaultLanguage').value='de';await form.onsubmit({preventDefault(){}});const request=f.calls.find(c=>c.options?.method==='PUT');assert.equal(request.url,'/api/tenants/current/settings');assert.equal(request.options.headers['Content-Type'],'application/json');assert.deepEqual(JSON.parse(request.options.body),{name:'Renamed synthetic',defaultLanguage:'de'});});
