package de.corporate.lc.document.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import de.corporate.lc.document.api.*;
import de.corporate.lc.document.domain.*;
import de.corporate.lc.document.repository.DocumentDraftRepository;
import de.corporate.lc.lc.repository.LetterOfCreditRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.*;

@Service
public class DocumentDraftService {
    private final DocumentDraftRepository drafts; private final LetterOfCreditRepository lcs; private final ObjectMapper json; private final GeneratedDocumentService generated; private final DocumentApprovalPolicyService approvalPolicy;
    public DocumentDraftService(DocumentDraftRepository drafts,LetterOfCreditRepository lcs,ObjectMapper json,GeneratedDocumentService generated,DocumentApprovalPolicyService approvalPolicy){this.drafts=drafts;this.lcs=lcs;this.json=json;this.generated=generated;this.approvalPolicy=approvalPolicy;}
    @Transactional(readOnly=true) public List<DocumentDraftView> list(UUID lcId){lcs.findById(lcId).orElseThrow();return drafts.findByLcIdOrderByUpdatedAtDesc(lcId).stream().map(this::view).toList();}
    @Transactional public DocumentDraftView create(UUID lcId,GeneratedDocumentRequest request,String username){lcs.findById(lcId).orElseThrow();DocumentDraft draft=new DocumentDraft();draft.setLcId(lcId);draft.setCreatedBy(username);draft.setUpdatedBy(username);apply(draft,request);return view(drafts.save(draft));}
    @Transactional public DocumentDraftView update(UUID lcId,UUID id,GeneratedDocumentRequest request,String username){DocumentDraft draft=one(lcId,id);editable(draft);if(!username.equalsIgnoreCase(draft.getCreatedBy()))throw new IllegalStateException("Nur der Ersteller kann den eigenen Entwurf bearbeiten.");apply(draft,request);draft.setUpdatedBy(username);draft.setUpdatedAt(LocalDateTime.now());return view(draft);}
    @Transactional public DocumentDraftView status(UUID lcId,UUID id,DocumentDraftStatus status,String username){DocumentDraft draft=one(lcId,id);if(draft.getStatus()==DocumentDraftStatus.FINAL)throw new IllegalStateException("Finalisierte Dokumententwürfe sind gesperrt.");boolean valid=draft.getStatus()==DocumentDraftStatus.DRAFT&&status==DocumentDraftStatus.SUBMITTED||draft.getStatus()==DocumentDraftStatus.SUBMITTED&&(status==DocumentDraftStatus.DRAFT||status==DocumentDraftStatus.REVIEWED)||draft.getStatus()==DocumentDraftStatus.REVIEWED&&status==DocumentDraftStatus.FINAL;if(!valid)throw new IllegalArgumentException("Dieser Statuswechsel ist nicht zulässig.");if(status!=DocumentDraftStatus.DRAFT){var validation=validation(lcId,request(draft));if(!validation.blockers().isEmpty())throw new IllegalStateException("Der Entwurf enthält noch Abweichungen: "+String.join("; ",validation.blockers()));}if(status==DocumentDraftStatus.SUBMITTED){if(!username.equalsIgnoreCase(draft.getCreatedBy()))throw new IllegalStateException("Nur der Ersteller kann den Entwurf zur Prüfung einreichen.");draft.setSubmittedBy(username);}if(status==DocumentDraftStatus.DRAFT){if(!username.equalsIgnoreCase(draft.getCreatedBy()))throw new IllegalStateException("Nur der Ersteller kann den Entwurf zurückziehen.");draft.setSubmittedBy(null);draft.setCheckedBy(null);draft.setCheckedAt(null);draft.setApprovalsJson("[]");draft.setRequiredApprovals(1);}if(status==DocumentDraftStatus.REVIEWED){requireDifferent(username,draft.getCreatedBy(),"Der Ersteller darf den eigenen Entwurf nicht prüfen.");draft.setCheckedBy(username);draft.setCheckedAt(LocalDateTime.now());var lc=lcs.findById(lcId).orElseThrow();draft.setRequiredApprovals(approvalPolicy.requiredApprovals(lc.getAmount(),lc.getCurrency()));draft.setApprovalsJson("[]");draft.setApprovedBy(null);draft.setApprovedAt(null);}if(status==DocumentDraftStatus.FINAL){requireDifferent(username,draft.getCreatedBy(),"Der Ersteller darf den eigenen Entwurf nicht freigeben.");requireDifferent(username,draft.getCheckedBy(),"Vier-Augen-Prinzip: Prüfer und Freigeber müssen unterschiedliche Benutzer sein.");List<String> approvals=approvalUsers(draft);if(approvals.stream().anyMatch(user->user.equalsIgnoreCase(username)))throw new IllegalStateException("Dieser Benutzer hat das Dokument bereits freigegeben.");approvals.add(username);try{draft.setApprovalsJson(json.writeValueAsString(approvals));}catch(JsonProcessingException e){throw new IllegalStateException("Freigaben konnten nicht gespeichert werden.",e);}if(approvals.size()>=draft.getRequiredApprovals()){draft.setStatus(DocumentDraftStatus.FINAL);draft.setApprovedBy(username);draft.setApprovedAt(LocalDateTime.now());}}if(status!=DocumentDraftStatus.FINAL||draft.getStatus()!=DocumentDraftStatus.FINAL)draft.setStatus(status==DocumentDraftStatus.FINAL?DocumentDraftStatus.REVIEWED:status);draft.setUpdatedBy(username);draft.setUpdatedAt(LocalDateTime.now());return view(draft);}
    @Transactional public DocumentView generate(UUID lcId,UUID id,String format)throws IOException{DocumentDraft draft=one(lcId,id);if(draft.getStatus()!=DocumentDraftStatus.FINAL)throw new IllegalStateException("Das Dokument muss vor der Ausgabe finalisiert werden.");GeneratedDocumentRequest request=request(draft);return "DOCX".equalsIgnoreCase(format)?generated.createDocx(lcId,request):generated.create(lcId,request);}
    @Transactional public void delete(UUID lcId,UUID id){DocumentDraft draft=one(lcId,id);editable(draft);drafts.delete(draft);}
    private void apply(DocumentDraft draft,GeneratedDocumentRequest request){draft.setDocumentType(request.type());draft.setDocumentNumber(request.documentNumber().trim());try{draft.setDataJson(json.writeValueAsString(request));}catch(JsonProcessingException e){throw new IllegalArgumentException("Dokumentdaten konnten nicht gespeichert werden.",e);}}
    private DocumentDraft one(UUID lcId,UUID id){return drafts.findById(id).filter(d->d.getLcId().equals(lcId)).orElseThrow(()->new NoSuchElementException("Dokumententwurf nicht gefunden"));}
    private void editable(DocumentDraft draft){if(draft.getStatus()!=DocumentDraftStatus.DRAFT)throw new IllegalStateException("Eingereichte oder geprüfte Dokumententwürfe sind gesperrt. Der Ersteller muss sie zuerst zurückziehen.");}
    private GeneratedDocumentRequest request(DocumentDraft draft){try{return json.readValue(draft.getDataJson(),GeneratedDocumentRequest.class);}catch(JsonProcessingException e){throw new IllegalStateException("Gespeicherte Dokumentdaten sind beschädigt.",e);}}
    private DocumentDraftView view(DocumentDraft draft){var request=request(draft);List<String> approvals=approvalUsers(draft);if(approvals.isEmpty()&&draft.getStatus()==DocumentDraftStatus.FINAL&&draft.getApprovedBy()!=null)approvals=List.of(draft.getApprovedBy());return new DocumentDraftView(draft.getId(),draft.getLcId(),draft.getDocumentType(),draft.getDocumentNumber(),draft.getStatus(),draft.getVersion(),draft.getCreatedBy(),draft.getUpdatedBy(),draft.getSubmittedBy(),draft.getCheckedBy(),draft.getCheckedAt(),draft.getApprovedBy(),draft.getApprovedAt(),draft.getCreatedAt(),draft.getUpdatedAt(),request,approvals,approvals.size(),draft.getRequiredApprovals(),validation(draft.getLcId(),request));}
    private List<String> approvalUsers(DocumentDraft draft){try{return new ArrayList<>(json.readValue(draft.getApprovalsJson(),json.getTypeFactory().constructCollectionType(List.class,String.class)));}catch(JsonProcessingException e){throw new IllegalStateException("Gespeicherte Freigaben sind beschädigt.",e);}}
    private void requireDifferent(String username,String other,String message){if(other==null||username.equalsIgnoreCase(other))throw new IllegalStateException("Vier-Augen-Prinzip: "+message);}
    private DocumentDraftValidation validation(UUID lcId,GeneratedDocumentRequest request){var lc=lcs.findById(lcId).orElseThrow();List<String> blockers=new ArrayList<>(),warnings=new ArrayList<>();if(lc.getExpiryDate()!=null&&request.documentDate().isAfter(lc.getExpiryDate()))blockers.add("Dokumentdatum liegt nach dem LC-Ablauf "+lc.getExpiryDate()+".");if(lc.getIssueDate()!=null&&request.documentDate().isBefore(lc.getIssueDate()))warnings.add("Dokumentdatum liegt vor dem Ausstellungsdatum des LC.");var items=request.items()==null?List.<GeneratedDocumentItemRequest>of():request.items();if((request.type()==DocumentType.COMMERCIAL_INVOICE||request.type()==DocumentType.PACKING_LIST)&&items.isEmpty())warnings.add("Keine strukturierten Warenpositionen erfasst.");if(items.stream().anyMatch(item->item.description()==null||item.description().isBlank()))blockers.add("Mindestens eine Position enthält keine Warenbeschreibung.");if(request.type()==DocumentType.COMMERCIAL_INVOICE){var sum=items.stream().map(GeneratedDocumentItemRequest::amount).filter(Objects::nonNull).reduce(java.math.BigDecimal.ZERO,java.math.BigDecimal::add);if(lc.getAmount()!=null&&sum.signum()>0&&sum.compareTo(lc.getAmount())>0)blockers.add("Positionssumme "+sum+" überschreitet den LC-Betrag "+lc.getAmount()+" "+lc.getCurrency()+".");else if(lc.getAmount()!=null&&sum.signum()>0&&sum.compareTo(lc.getAmount())!=0)warnings.add("Positionssumme "+sum+" weicht vom LC-Betrag "+lc.getAmount()+" "+lc.getCurrency()+" ab.");}if(request.type()==DocumentType.PACKING_LIST)for(var item:items){if(item.packages()==null||item.packages()<=0)warnings.add("Position "+safe(item.position())+": Packstückzahl fehlt.");if(item.netWeight()==null||item.grossWeight()==null)warnings.add("Position "+safe(item.position())+": Netto- oder Bruttogewicht fehlt.");else if(item.grossWeight().compareTo(item.netWeight())<0)blockers.add("Position "+safe(item.position())+": Bruttogewicht ist kleiner als Nettogewicht.");}String goods=lc.getAdditionalFields().entrySet().stream().filter(e->e.getKey().contains("45A")||e.getKey().contains("45B")).map(Map.Entry::getValue).findFirst().orElse(null);if(goods!=null&&!items.isEmpty()&&items.stream().noneMatch(item->similar(goods,item.description())))warnings.add("Warenbeschreibung konnte der gültigen LC-Fassung nicht sicher zugeordnet werden.");return new DocumentDraftValidation(blockers.isEmpty()?(warnings.isEmpty()?"GREEN":"YELLOW"):"RED",List.copyOf(blockers),List.copyOf(warnings));}
    private boolean similar(String expected,String actual){if(actual==null)return false;Set<String> left=tokens(expected),right=tokens(actual);long overlap=left.stream().filter(right::contains).count();return overlap>=Math.min(2,Math.min(left.size(),right.size()));}
    private Set<String> tokens(String value){Set<String> result=new HashSet<>();if(value!=null)for(String token:value.toLowerCase(Locale.ROOT).split("[^a-z0-9]+"))if(token.length()>3)result.add(token);return result;}
    private String safe(String value){return value==null||value.isBlank()?"?":value;}
}
