package de.corporate.lc.document.service;

import com.deepoove.poi.XWPFTemplate;
import de.corporate.lc.document.api.GeneratedDocumentRequest;
import de.corporate.lc.document.domain.DocumentType;
import de.corporate.lc.lc.domain.LetterOfCredit;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

@Service
public class DocxTemplateService {
    public byte[] render(LetterOfCredit lc, GeneratedDocumentRequest request) throws IOException {
        byte[] template = template(request.type());
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("title", request.type() == DocumentType.COMMERCIAL_INVOICE ? "COMMERCIAL INVOICE" : "PACKING LIST");
        data.put("documentNumber", value(request.documentNumber()));
        data.put("documentDate", request.documentDate().toString());
        data.put("lcReference", value(lc.getReference()));
        data.put("beneficiary", value(lc.getBeneficiary()));
        data.put("applicant", value(lc.getApplicant()));
        data.put("description", value(request.description()));
        data.put("quantity", value(request.quantity()));
        data.put("amount", value(lc.getCurrency()) + " " + (lc.getAmount() == null ? "-" : lc.getAmount()));
        data.put("packages", request.packages() == null ? "-" : request.packages().toString());
        data.put("netWeight", request.netWeight() == null ? "-" : request.netWeight() + " kg");
        data.put("grossWeight", request.grossWeight() == null ? "-" : request.grossWeight() + " kg");
        data.put("notes", value(request.notes()));
        try (XWPFTemplate compiled = XWPFTemplate.compile(new ByteArrayInputStream(template)).render(data);
             ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            compiled.write(output);
            return output.toByteArray();
        }
    }

    private byte[] template(DocumentType type) throws IOException {
        try (XWPFDocument document = new XWPFDocument(); ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            XWPFParagraph heading = document.createParagraph();
            heading.setStyle("Title");
            heading.createRun().setText("{{title}}");
            field(document, "Document No.", "documentNumber");
            field(document, "Date", "documentDate");
            field(document, "LC Reference", "lcReference");
            field(document, "Seller / Beneficiary", "beneficiary");
            field(document, "Buyer / Applicant", "applicant");
            field(document, "Description", "description");
            field(document, "Quantity", "quantity");
            if (type == DocumentType.COMMERCIAL_INVOICE) field(document, "Amount", "amount");
            else {
                field(document, "Packages", "packages");
                field(document, "Net weight", "netWeight");
                field(document, "Gross weight", "grossWeight");
            }
            field(document, "Notes", "notes");
            document.createParagraph().createRun().setText("Generated by Corporate LC Manager");
            document.write(output);
            return output.toByteArray();
        }
    }

    private void field(XWPFDocument document, String label, String key) {
        XWPFParagraph paragraph = document.createParagraph();
        paragraph.createRun().setBold(true);
        paragraph.getRuns().get(0).setText(label + ": ");
        paragraph.createRun().setText("{{" + key + "}}");
    }

    private String value(String value) { return value == null || value.isBlank() ? "-" : value.trim(); }
}
