package de.ostms.lc.lc.service;
import de.ostms.lc.lc.domain.*;import de.ostms.lc.lc.repository.*;import de.ostms.lc.swift.Mt707Parser;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;import java.util.regex.Pattern;
@Service public class AmendmentService{private static final String EFFECTIVE_GOODS="45A - gültige Warenbeschreibung",EFFECTIVE_CONDITIONS="47A - gültige Zusatzbedingungen";private final AmendmentRepository amendments;private final LetterOfCreditRepository lcs;private final Mt707Parser parser;public AmendmentService(AmendmentRepository a,LetterOfCreditRepository l,Mt707Parser p){amendments=a;lcs=l;parser=p;}
/** Stores the amendment as PENDING. The credit is changed only when the amendment is accepted. */
@Transactional public Amendment importMt707(String raw){var parsed=parser.parse(raw);LetterOfCredit lc=findTarget(parsed).orElseThrow(()->new IllegalArgumentException("Original-Akkreditiv nicht gefunden. Geprüfte Referenzen: "+String.join(", ",parsed.references())));Amendment a=parsed.amendment();if(a.getAmendmentNumber()==null||a.getAmendmentNumber().isBlank())throw new IllegalArgumentException("Amendment-Nummer :26E: fehlt.");if(amendments.existsByLetterOfCreditIdAndAmendmentNumber(lc.getId(),a.getAmendmentNumber()))throw new IllegalArgumentException("Dieses Amendment wurde bereits importiert.");a.setLetterOfCredit(lc);a.setStatus("PENDING");return amendments.save(a);}
/** The dossier named by :21:, :23: or :20: (in that order of preference); several different dossiers are an error, none is empty. */
public Optional<LetterOfCredit> findTarget(Mt707Parser.Parsed parsed){var found=new ArrayList<LetterOfCredit>();for(String reference:parsed.references())lcs.findForAmendment(reference).ifPresent(candidate->{if(found.stream().noneMatch(x->x==candidate||(x.getId()!=null&&x.getId().equals(candidate.getId()))))found.add(candidate);});if(found.size()>1)throw new IllegalArgumentException("Die Referenzen der Änderung ("+String.join(", ",parsed.references())+") passen zu mehreren Akten. Bitte manuell zuordnen.");return found.stream().findFirst();}
/** Accepted by the beneficiary: the changes take effect on the credit now. Earlier amendments must be decided first. */
@Transactional public Amendment accept(UUID amendmentId,String user,String comment){Amendment a=pending(amendmentId);LetterOfCredit lc=a.getLetterOfCredit();requireEarlierDecided(a);a.setBeforeState(AmendmentSnapshot.capture(lc));apply(lc,a);if(lc.getAmount()!=null&&lc.getAmount().signum()<0)throw new IllegalArgumentException("Der geänderte LC-Betrag darf nicht negativ sein.");a.setAfterState(AmendmentSnapshot.capture(lc));a.decide("ACCEPTED",user,comment);lcs.save(lc);return amendments.save(a);}
/** Rejected: the credit stays as it is. */
@Transactional public Amendment reject(UUID amendmentId,String user,String comment){Amendment a=pending(amendmentId);a.decide("REJECTED",user,comment);return amendments.save(a);}
private Amendment pending(UUID id){Amendment a=amendments.findById(id).orElseThrow(()->new NoSuchElementException("Änderung nicht gefunden."));if(!a.isPending())throw new IllegalStateException("Diese Änderung wurde bereits entschieden ("+("ACCEPTED".equals(a.getStatus())?"angenommen":"abgelehnt")+").");return a;}
private void requireEarlierDecided(Amendment a){OptionalInt number=number(a.getAmendmentNumber());if(number.isEmpty())return;for(Amendment other:amendments.findByLetterOfCreditIdOrderByImportedAtDesc(a.getLetterOfCredit().getId())){if(other==a||!other.isPending())continue;OptionalInt n=number(other.getAmendmentNumber());if(n.isPresent()&&n.getAsInt()<number.getAsInt())throw new IllegalStateException("Änderung Nr. "+n.getAsInt()+" ist noch offen und muss zuerst angenommen oder abgelehnt werden.");}}
static OptionalInt number(String value){if(value==null)return OptionalInt.empty();String digits=value.replaceAll("[^0-9]","");return digits.isEmpty()||digits.length()>6?OptionalInt.empty():OptionalInt.of(Integer.parseInt(digits));}
void apply(LetterOfCredit lc,Amendment a){if(a.getNewExpiryDate()!=null){lc.setExpiryDate(a.getNewExpiryDate());if(a.getNewExpiryPlace()!=null&&!a.getNewExpiryPlace().isBlank())lc.setExpiryPlace(a.getNewExpiryPlace());}if(a.getNewLatestShipmentDate()!=null)lc.setLatestShipmentDate(a.getNewLatestShipmentDate());if(a.getAmountIncrease()!=null&&lc.getAmount()!=null)lc.setAmount(lc.getAmount().add(a.getAmountIncrease()));if(a.getAmountDecrease()!=null&&lc.getAmount()!=null)lc.setAmount(lc.getAmount().subtract(a.getAmountDecrease()));applyDocumentChanges(lc,a.getChangedDocuments());applyTextChanges(lc,EFFECTIVE_GOODS,"45A",a.getChangedGoods());applyTextChanges(lc,EFFECTIVE_CONDITIONS,"47A",a.getChangedConditions());applyOtherChanges(lc,a.getOtherChanges());}
/** :59: replaces the beneficiary; every other field replaces the value of the same SWIFT field in the additional fields. */
void applyOtherChanges(LetterOfCredit lc,String json){if(json==null||json.isBlank())return;Map<String,String> changes;try{changes=new com.fasterxml.jackson.databind.ObjectMapper().readValue(json,new com.fasterxml.jackson.core.type.TypeReference<LinkedHashMap<String,String>>(){});}catch(com.fasterxml.jackson.core.JsonProcessingException invalid){throw new IllegalStateException("Gespeicherte Änderungen sind ungültig.");}changes.forEach((tag,value)->{if("59".equals(tag))lc.setBeneficiary(value);else lc.getAdditionalFields().put(tag+" - "+de.ostms.lc.swift.Mt700Parser.label(tag),value);});}
void applyDocumentChanges(LetterOfCredit lc,String changes){if(changes==null||changes.isBlank())return;List<String> current=new ArrayList<>(lc.getRequiredDocuments());boolean replace=replaceAll(changes);if(replace)current.clear();for(String raw:changes.split("\\R")){String line=raw.trim();if(line.isBlank()||replacementMarker(line))continue;if(addition(line)){String value=instructionValue(line);if(!value.isBlank()&&current.stream().noneMatch(existing->same(existing,value)))current.add(value);}else if(deletion(line)){String value=instructionValue(line);current.removeIf(existing->same(existing,value));}else if(replace)current.add(line);}lc.setRequiredDocuments(current);}
void applyGoodsChanges(LetterOfCredit lc,String changes){applyTextChanges(lc,EFFECTIVE_GOODS,"45A",changes);}void applyTextChanges(LetterOfCredit lc,String key,String originalCode,String changes){if(changes==null||changes.isBlank())return;LcCondition condition="45A".equals(originalCode)?LcCondition.GOODS_DESCRIPTION:LcCondition.ADDITIONAL_CONDITIONS;String original=LcConditions.value(lc,condition).orElse("");List<String> current=new ArrayList<>(Arrays.stream(original.split("\\R")).map(String::trim).filter(value->!value.isBlank()).toList());boolean replace=replaceAll(changes);if(replace)current.clear();for(String raw:changes.split("\\R")){String line=raw.trim();if(line.isBlank()||replacementMarker(line))continue;if(addition(line)){String value=instructionValue(line);if(!value.isBlank())current.add(value);}else if(deletion(line)){String value=instructionValue(line);current.removeIf(existing->same(existing,value));}else if(replace)current.add(line);}String effective=String.join("\n",current);lc.getAdditionalFields().put(key,effective);lc.getConditions().put(condition,effective);}
private Optional<String> swiftField(String raw,String code){if(raw==null)return Optional.empty();var matcher=Pattern.compile("(?ms)^:"+Pattern.quote(code)+":\\s*(.*?)(?=^:[0-9]{2}[A-Z]?:|\\z)").matcher(raw);return matcher.find()?Optional.of(matcher.group(1).trim()):Optional.empty();}private boolean replaceAll(String value){String upper=value.toUpperCase(Locale.ROOT);return upper.contains("/REPALL/")||upper.contains("REPLACE ALL");}private boolean replacementMarker(String value){return value.equalsIgnoreCase("/REPALL/")||value.equalsIgnoreCase("REPLACE ALL");}private boolean addition(String value){return value.startsWith("+")||value.toUpperCase(Locale.ROOT).startsWith("/ADD/");}private boolean deletion(String value){return value.startsWith("-")||value.toUpperCase(Locale.ROOT).startsWith("/DELETE/");}private String instructionValue(String value){if(value.startsWith("+")||value.startsWith("-"))return value.substring(1).trim();int slash=value.indexOf('/',1);return slash>=0?value.substring(slash+1).trim():"";}private boolean same(String left,String right){return left.replaceAll("[^A-Za-z0-9]","").equalsIgnoreCase(right.replaceAll("[^A-Za-z0-9]",""));}public List<Amendment> forLc(UUID id){return amendments.findByLetterOfCreditIdOrderByImportedAtDesc(id);}}
